HadoukenIO/core

src/browser/api/application.js
@StevenEBarbaro @HarsimranSingh  @rdepena 
This fixes the double setTrayIcon crash as well as ensures that the icon teardown happens before any possible failures in the subscription unhook. The subscriptions not tearing down correctly should be looked at as a separate issue as it is just try/caught here.
[tests well](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/591376805114ac10ca6db382) all but notification/onshow and preload pass in isolation
=> RUN-2985 Hotfix tray icon teardown

src/browser/api/application.js, src/browser/core_state.js, src/browser/log.ts, src/browser/navigation_validation.ts
For `executeJavaScript` you have to be in the parenting lineage of an app (or window). Restarting was breaking this because we were storing the parent info on the app obj that was being cleaned up on the close event. This PR moves the `parentUuid` up to the meta `app` object that persists through the close / restart.
[tests well](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/590b263d5114ac10ca6db32e)
[added test](https://testing-dashboard.openfin.co/#/app/tests/58b5e799b4be9d42a7399632/edit)
=> RUN-2807 reload breaks parenting model

Gruntfile.js, index.js, package.json, src/browser/connection_manager.ts, src/browser/pending_subscriptions.ts
This PR sets the base layer for supporting subscriptions to cross-runtime events for runtimes or apps that haven't been launched yet.
My next PR (programmatically launching apps via RVM) will depend on these code changes.
In the future it needs to be improved, but for now, it is known to work for needed events.
✅  [Tests OK](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5910c0105114ac10ca6db36e) (one is an inconsistent timeout, but doesn't come up when singled out)
=> RUN-2962 adds ability to subscribe to future cross-runtime events

src/browser/api/system.js
@wenjunche @StevenEBarbaro @HarsimranSingh @joneit @whyn07m3 @datamadic 
* args no longer required 
* accept download id from the renderer.
[Test results](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5910bfda5114ac10ca6db36d) 
[related javascript-adapter PR](https://github.com/openfin/javascript-adapter/pull/303)
=> RUN-2837 download id now generated at the renderer, prevents timing issues on subscription.

package.json, src/browser/api/application.js, src/browser/api_protocol/api_handlers/application.js, src/browser/core_state.js, src/browser/rvm/utils.ts
ℹ️  This PR adds ability to launch app from a manifest programmatically. It supports multi-runtime app creation (you get a success callback once the app in another runtime launches).
✅  [Tests okay](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5910d6c45114ac10ca6db370)
👫  [Coupled with this PR in javascript-adapter](https://github.com/openfin/javascript-adapter/pull/304)
➕  New tests (will publish at the right time):
1. [Application.createFromManifest](https://testing-dashboard.openfin.co/#/app/tests/5911cbc55114ac10ca6db372/edit)
2. [Application.createFromManifest T2](https://testing-dashboard.openfin.co/#/app/tests/5910e1105114ac10ca6db371/edit)
3. [Application.run (for Application.createFromManifest)](https://testing-dashboard.openfin.co/#/app/tests/5911ccbe5114ac10 …
=> RUN-2913 adds ability to launch apps from manifest programmatically

src/browser/api_protocol/api_handlers/api_policy_processor.ts
These two lines in `src/browser/api_protocol/api_handlers/api_policy_processor.ts` were transformed incorrectly in RUN-2948 and have been corrected here:
* Line [264](https://github.com/HadoukenIO/core/pull/22/files#diff-913a464613b1e54fcf96f6ae20c07944R264)
* Line [267](https://github.com/HadoukenIO/core/pull/22/files#diff-913a464613b1e54fcf96f6ae20c07944R267)
=> Fix error introduced by #22

Gruntfile.js, index.js, src/browser/api/application.js, src/browser/api/external_application.ts, src/browser/api/notifications/subscriptions.ts, src/browser/api/system.js, src/browser/api/window.js, src/browser/api_protocol/api_handlers/application.js, src/browser/api_protocol/api_handlers/authorization.js, src/browser/api_protocol/api_handlers/interappbus.js, src/browser/api_protocol/transport_strategy/ws_strategy.ts, src/browser/external_window_event_adapter.js, src/browser/navigation_validation.ts, src/browser/of_events.ts, src/browser/port_discovery.ts, src/browser/process_tracker.js, src/browser/remote_subscriptions.ts, src/browser/rvm/rvm_message_bus.ts, src/browser/subscription_manager.js, src/browser/transports/socket_server.js, src/common/route.ts, test/routes.test.ts
Yes, 21 files, but **Don't Panic!** because most of the edits one-to-one conversion from route literal to the new call.
I reviewed all the calls for accuracy. [Tested](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59275fc5998bc04e20cc6c8b) clean.
**Caveat:** The only literal route strings remaining in the code are in `src/renderer/api-decorator.js` (because of that file has no access to `require()`).
Generic route:
```js
'channel/topic/subtopic/subsubtopic'
```
Notes:
* Sometimes in our code "channel" is called `topic`; and "topic" is called `type`
* Window routes often end in `uuid/name`; they very occasionally end in `uuid-name`; and sometimes they end in something entirely different
* calling syntax designed for convenience/readability
* although `route` not a verb …
=> RUN-3020: Normalize route string fabrication

package.json
runtime-p2p updated from openfin/js-adapter to hadoukenio/node-adapter
=> moved from the js-adapter to the hadouken node-adapter.

index.js, src/browser/api/application.js, src/browser/api_protocol/api_handlers/authorization.js, src/browser/core_state.js, src/browser/rvm/rvm_message_bus.ts, src/modules.d.ts, test/rvm_message_bus.test.ts
* RUN-2846 working on testing
* RUN-2846 rebasing to develop
* RUN-2846 send the license info on app run and external adapter connected
* RUN-2846 better name for ExternalLicenseInfo
* RUN-2966 expose webSecurity (#43)
* RUN-2846 stamp the license key on the app meta object, use local license if provided
* RUN-2846 removed redundant setLicenseKey call
* RUN-2846 test file cleanup
* RUN-2846 updated for import statements
=> RUN-2846 Send licensing info

index.js, src/browser/api/application.js, src/browser/rvm/rvm_message_bus.ts
Do not double stringify rvm event payloads
[tests well](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/593ec71efe393b3a13633999) all fails are also on vanilla build
=> Hotfix RVM Events

src/browser/api/application.js, src/browser/rvm/rvm_message_bus.ts
[tests](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/593ebc47d7ae0a6fab034812) All failing tests (except for note close on show) also fail on a vanilla win10  6.49.21.19
=> Hotfix rvm event payloads

index.js, src/browser/api/application.js, src/browser/api_protocol/api_handlers/authorization.js, src/browser/core_state.js, src/browser/rvm/rvm_message_bus.ts, test/electron.ts, test/log.test.ts, test/rvm_message_bus.test.ts
@StevenEBarbaro @HarsimranSingh @rdepena @whyn07m3 
So why the funny `{data: {...}}` shape on the register license call? Testing. It makes it easier to override the dynamic values in a mock situation. 
[tests well](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59442a020f8f4a3476957134)
=> Bugfix/remote connection spawned app licenses 6.49.21/staging

src/browser/api/application.js, src/browser/api_protocol/api_handlers/authorization.js, src/browser/core_state.js, src/browser/rvm/rvm_message_bus.ts, test/electron.ts, test/log.test.ts, test/rvm_message_bus.test.ts
@StevenEBarbaro @HarsimranSingh @rdepena @whyn07m3 
So why the funny `{data: {...}}` shape on the register license call? Testing. It makes it easier to override the dynamic values in a mock situation. 
[tests well](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59442a020f8f4a3476957134)
=> RUN-3044 merge into 7.53.21/staging

Gruntfile.js, package.json, src/browser/core_state.ts, src/modules.d.ts, src/shapes.ts
Changes:
• Typed out core state with no logic changes
• Removed unused function `remoteAppPropDecorator`
• Minor stylistic changes
• Renamed a few parameters and variables
---
Tests results:
✅  [Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59383deb998bc04e20cc6cd5)
✅  [Windows 8](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59384226998bc04e20cc6cd8)
✅  [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59383da9998bc04e20cc6cd3)
=> RUN-3040 moved core_state JS to TS

src/browser/api/application.js
The ticket reported did not mention this but @datamadic noticed it and its a quick fix.
@StevenEBarbaro @HarsimranSingh @datamadic @whyn07m3 check it out.
=> RUN-3048 fixed issue where startup errors were printing a template string

index.js, src/browser/api/application.js, src/browser/convert_options.js
The port discovery message will now only be sent out if the initial app load is successful. A typo in the `noerrdialogs` guard was fixed as well. 
@wenjunche I tested with .NET and Node adapters and it seems to behave, can you check against Java? 
@rdepena You had expressed some concern with moving the message here, can you remind me what it was 😄? 
[tests well](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/594d3a830c10170217365886) all fails pass in isolation
=>  RUN-2989 bad port discovery message / no error dialogs 

src/browser/api_protocol/api_handlers/application.js, src/browser/api_protocol/api_handlers/window.js, src/browser/api_protocol/index.ts
Currently, API handler maps are located inside classes. I need the maps (App and Window) out exported without the need to instantiate anything (for my next PR).
This PR shows big changes because of indentation: everything indented and inside the class is now moved out of it, hence, no indentation.
Tests results (typical errors for vanilla):
• [Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5954002f0c1017021736590b)
• [Windows 8](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5954002a0c1017021736590a)
• [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5954012c0c1017021736590c)
=> RUN-3074 exposes Application and Window API maps

src/browser/api_protocol/api_handlers/api_protocol_base.ts, src/browser/api_protocol/index.ts
Refactored mesh middlewear initiation so that we can control the middlewear handler queue.
This is needed for my future PR.
Test results are good (typical vanilla build errors)
[Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/595530e10c10170217365912)
[Windows 8](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/595530ec0c10170217365913)
[Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/595532710c10170217365914)
=> RUN-3081 middleware refactor to control handler queue

src/browser/api_protocol/api_handlers/api_middleware.ts, src/browser/api_protocol/api_handlers/middleware_entity_existence.ts, src/browser/api_protocol/index.ts
Added a new middleware that will check for existence of applications and windows before proceeding with an API call execution. Will fire an error callback if an app or a window doesn't exist. This will match v5 behavior.
Middleware handler queue becomes:
API policy => Mesh / multi-runtime => Entity check (this PR) => API Execution
Added 2 new tests: 1 test for one of the application APIs and 1 test for one of the window APIs. Will publish them once the PR is merged and a build is produced.
• [Application.isRunning (called on non-existent app)](https://testing-dashboard.openfin.co/#/app/tests/5952a4b20c101702173658c4/edit)
• [Window.focus (called on non-existent window)](https://testing-dashboard.openfin.co/#/app/tests/5952a5090c101702173658c5/edit)
Test results (typical for vanilla): …
=> RUN-2452 Fire error callbacks for nonexistent apps and windows (where appropriate)

index.js, src/browser/transports/socket_server.js
Ensure that external adapters can connect. 
[tests well](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/596e6ebda3c7663182518f98)
=> RUN-3154 do not spawn the socket server twice [7.53.22/staging]

src/browser/api/window.js
[before change](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/596e722aa3c7663182518f99)
[including change](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/596e731fa3c7663182518f9c)
TODO as  RUN-3161 - Refactor applyAdditionalOptionsToWindowOnVisible to also use `ready-to-show`
=> RUN-3160 8.56.*.* - Opacity not applied on window construction

src/browser/transports/socket_server.js
Fixed issue where if the port was already in use we would not start the socket server.
#104 into 7/Staging
@datamadic @StevenEBarbaro 
Tests Pending
=> RUN-3167 Socket server fix

src/browser/api/application.js, src/browser/api/window.js, src/browser/api_protocol/api_handlers/window.js, src/renderer/api-decorator.js
Local tests (even against stable) have been less than desirable, but it looks about the same (+/- the additional tests) 
[PRtests](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/597b4d2ea3c7663182519004)
[stable tests](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/597b51fea3c7663182519005)
[additional tests](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/597ba309a3c766318251900b)
=> RUN-3165 remove reliance on the renderer for unload events hotfix

src/browser/api/window.js, src/browser/api_protocol/api_handlers/window.js, src/renderer/api-decorator.js
https://github.com/HadoukenIO/core/pull/119/files for develop.
[tests well*](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/597f86e4a3c7663182519015)
*I am getting local fails with the same build w/o my runtime + core changes as well
=> RUN-3165 remove reliance on the renderer for unload events 7.53.22/staging

src/browser/api_protocol/api_handlers/mesh_middleware.ts
Issue:
IAB Publish always returns success, mesh middleware would ack on each success in turn returning multiple ack packages to the originator.
[Test run](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59795462a3c7663182518fdf)
New node-adapter test pending.
@StevenEBarbaro @HarsimranSingh @whyn07m3 @joneit @datamadic
=> RUN-3168 Multiple success acks on IAB Publish

src/browser/api_protocol/api_handlers/authorization.js, src/browser/api_protocol/index.ts
ℹ️ Adds auth middleware that prevents unauthenticated WebSocket connections making API calls.
---
➕  **New Test**
• [WS API call w/o authentication](https://testing-dashboard.openfin.co/#/app/tests/597f8383a3c7663182519014/edit)
---
⚠️ **Diff** for `/api_handlers/authorization.js` file looks crazy (because of indentation changes throughout the file), but the only changes to that file are:
1. Made it NOT be a class
2. added `init` function in place of previously having to instantiate class
3. added auth middleware function `isConnectionAuthenticated` and its registration in `registerMiddleware`
---
✅  **Test Results** *(ignore new multi-preload scripts test errors, they are invalid)*
• [Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/597f90748b67d4711b9a9610)
• …
=> RUN-3120 prevent API calls from unauthenticated WS connections

src/browser/api/window.js
ℹ️  Adds ability to query for preload state by retrieving window info
🔗 **Paired** with [this PR](https://github.com/openfin/javascript-adapter/pull/318) which documents new window info payload
---
➕ New test:
• [Window.getInfo T2 (preloadState)](https://testing-dashboard.openfin.co/#/app/tests/59774ef9a3c7663182518fca/edit)
---
Local tests pass. **No public test results** because this PR depends on the [previous PR](https://github.com/HadoukenIO/core/pull/128). Will post them after previous PR is consumed.
=> RUN-3125 added ability to query preload state

index.js, src/browser/api/system.js, src/browser/api_protocol/api_handlers/system.js
@StevenEBarbaro @rdepena @joneit 
[needs adapter](https://github.com/openfin/javascript-adapter/pull/322)
tests well (parody with vanilla for me):
[general](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/598c6d8fd2a02971da3a6299)
[initially failed...](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/598c7b68d2a02971da3a62a9)
[additional](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/598c7c5ed2a02971da3a62aa)
=> RUN-3140 RUN-3141 additional logging calls

README.md
Microsoft has turned links for VS 2013 into a black hole. The VS 2015 build tools will let you build the project. Contains updated link & instruction.
=> VS 2013 is MIA, point to VS 2015 build tools for building on Windows

src/browser/convert_options.js, src/renderer/api-decorator.js
ℹ️   **Description**
Fixes support for falsy preload scripts
➕  **New test**
• [new Window (preload) (falsy value / reset)](https://testing-dashboard.openfin.co/#/app/tests/59944c83d2a02971da3a62d6/edit)
✅  **Test results**
• [Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/599492fed2a02971da3a62da)
• [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5994935bd2a02971da3a62db)
=> RUN-3265 fixed falsy preload

src/browser/api_protocol/api_handlers/authorization.js
Forwarded requests were being incorrectly flaged as not being authenticated.
=> RUN-3269 fixed the isConnectionAuthenticated check to include multi runtime

src/browser/api_protocol/api_handlers/middleware_entity_existence.ts
Tests are currently running...
=> RUN-3271 Ignore run-application for entity existence checks for now as it breaks behaviour contracts with Adapters.

src/renderer/api-decorator.js
Regression [**tests**](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/598de08ad2a02971da3a62bf) passed (no relevant fails).
=> RUN-3228 Remove unneeded `mustSucceed` preload script option

src/browser/api/system.js, src/browser/preload_scripts.ts, src/renderer/api-decorator.js
\[See sister [PR#330](https://github.com/openfin/javascript-adapter/pull/330) in openfin/javascript-adapter.]
@omerli points out local files normally bypass Chromium cache anyway and therefore _would always be reloaded on every page;_ and to aid app development, we should do the same. 
1. **Adjust logic to always reload local files** on `new Window({preload:'file://...'})`, even if already loaded by a previously created window.<br>
_Specifically:_ Local files (resources with `file://` scheme) are now _excepted_ from our _temporary_ work-around that generally _avoids_ re-fetching/loading previously loaded preload scripts. (Workaround to be removed by [RUN-3227](https://appoji.jira.com/browse/RUN-3227) once [RUN-3162](https://appoji.jira.com/browse/RUN-3162) is resolved.)<br>
_Caveat:_ …
=> RUN-3275 Always re/fetch local preload script files

src/browser/api/system.js, src/browser/api_protocol/api_handlers/authorization.js, src/browser/core_state.ts
Test results:
[Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/599f65a4d2a02971da3a6347
)
[Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/599f6542d2a02971da3a6346)
Also, fixed code in authorization.js according to [https://github.com/openfin/openfin/wiki/RVM-Protocol]().  created RUN-3290 to track the issue.
New versions of .net and Java adapters are required to test app asset APIs from external adapters.
=> RUN-3286 App assets API does not work if not launched by manifest

.jshintrc, index.js, src/browser/api/window.js, src/renderer/api-decorator.js
This PR only registers "shortcut" keys that are needed by the page.
Base on current `canary` (`8.56.24.3`).
[Tested](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/599ed18cd2a02971da3a633f) clean.
Previously designated "shortcut" keys were always registered as accelerators, although their handlers only took action as needed. This defect pre-empted the DOM events from firing for those keys so registered.
This improvement allows DOM event handler/listeners to catch these keys in `keydown` handler —
so long as they are not required per `options.accelerator`. This includes **F5**.
```js
function f5handler(e) {
if (e.keyCode === 116) console.log('F5 pressed');
}
document.addEventListener('keydown', f5handler); // "listener"
// or:
document.onkeydown = f5handler; // "handler" …
```
=> RUN-3136 Limit accelerator registration per options

src/browser/core_state.ts, src/shapes.ts
Changes for RUN-1939 got lost. 
Test Result 
[W10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59a72c47d2a02971da3a638b)
[W7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59a72b92d2a02971da3a638a)
REDI is waiting for this change.
=> RUN-3297: Support nonPersistent and nonPersistant

index.js, src/browser/api/system.js, src/browser/api_protocol/api_handlers/system.js
Adds the ability to toggle the verbosity levels programmaticly.
Needs [adapter PR](https://github.com/openfin/javascript-adapter/pull/328)
Needs [runtime PR](https://github.com/openfin/runtime/pull/582)
[tests](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/599668e5d2a02971da3a62e7) (fails passed in isolation / parody with vanilla build) 
[added tests](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59966fd0d2a02971da3a62ed)
=> RUN-3251 feature/toggle log levels

src/browser/api/window.js
Regression [test](https://en.wikipedia.org/wiki/File_URI_scheme)ed.
=> RUN-2905 win.show() restores maximized window

src/browser/preload_scripts.ts
This just avoids logging an error for what it is being validated as a malformed preload option.
Regression [tests](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59a8814fd2a02971da3a63a1) clean.
=> RUN-3299 Handle undefined preload option more gracefully

src/browser/animations.js, src/browser/api/window.js, src/browser/bounds_changed_state_tracker.js, src/browser/convert_options.js, src/shapes.ts
By adding a `smallWindow` flag to allow for very small frameless windows, the move and resize code needs to be updated to preserve bounds-changed and window groups functionality.
runtime: https://github.com/openfin/runtime/pull/608
javascript-adapter: https://github.com/openfin/javascript-adapter/pull/337
=> RUN-3284 Add smallWindow flag and update move/resize functions

src/browser/api/window.js
I saved the state of `ready-to-show` event-fired directly on the `browserWindow` object (much as we save `_options` there). Seems like a good place for it inasmuch as it reflects `browserWindow` state. Nonetheless I throw it out there: Is there a better place for (what can also be thought of as) a window instance var?
@HarsimranSingh @StevenEBarbaro How do we test this? Is there already a v8 test for this (that tests the existing `setTimeout` solution)?
Based on current `canary` (`runtime-v8.56.24.10`).
Regression [tested](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59a30434d2a02971da3a6365) clean.
=> RUN-3161 Wait for ready-to-show

index.js, src/browser/api/system.js, src/browser/log.ts, src/modules.d.ts, tslint.json
ℹ️  **About**
These changes switch logging level to verbose whenever the core is in the "diagnostics" mode
➕  **New test**
[fin.desktop.System.startCrashReporter (verbose logging)](https://testing-dashboard.openfin.co/#/app/tests/59aeb1aed2a02971da3a63a6/edit)
✅  **Test results**
[Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59af5ae6d2a02971da3a63bf)
[Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59af5c20d2a02971da3a63c0)
=> RUN-3143 always set logging level to 'verbose' when in diagnostics mode

src/browser/api/window.js
No longer waiting for the "no-show" `ready-to-show`.
Reverts #155 (RUN-3161).
Based on `8.56.24/staging` (currently aka `develop`).
Tested locally; I can see the resize options are properly applied now.
=> RUN-3336 revert ready-to-show refactor

src/renderer/main.js
Tests came back clean:
[Win 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59a876f8d2a02971da3a639d)
[Win 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59a87c0bd2a02971da3a639f)
=> Read javascript-adapter from dir and then asar; for ease of development

src/browser/api/system.js, src/browser/api_protocol/api_handlers/system.js, src/renderer/api-decorator.js
Issue was caused by returning to api-decorator `''` (empty string) for all missing scripts, which scripts were then executed "successfully" yielding `'succeeded`' status for each.
Fix was to:
1. Return `null` from `System` API ([here](https://github.com/HadoukenIO/core/pull/169/files#diff-f0315d374f54075fc6010e3dd131bea7R690)); and
2. Skip the `eval()` for such scripts in api-decorator by adding an `if` statement ([here](https://github.com/HadoukenIO/core/pull/169/files#diff-afd6093bc77cc147dad3d61fcfdec439R553)). This also skips updating the script status from `'load-failed'` to `'succeeded'`.
All the other edits in this PR have to do simplifying the `getSelectedPreloadScripts` API call to make proper use of `nack`.
=> RUN-3317 Missing preload script has "succeeded" status

src/renderer/api-decorator.js
@HarsimranSingh @rdepena @joneit 
Ensure that we are always getting the current option set. Also, rename the `getWindowOptions` call to `getCachedWindowOptions` as that is what its actually doing... there is a **required** sister [adapter PR here](https://github.com/openfin/javascript-adapter/pull/338).
[Tests well](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59b6da9d3d90dd51ca4f1011) compared to a [vanilla build](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59b6ddfa3d90dd51ca4f1012) 
Verify using the manual [test app](https://dl.openfin.co/services/download?fileName=Test%20Apps&config=http://test.openf.in/test_apps/config.json) go to the Window tab and under Options scroll to contextMenu
=> RUN-3306 add back the ability to toggle the context menu

src/browser/api/application.js, src/browser/preload_scripts.ts, src/common/timer.ts, src/renderer/api-decorator.js
To extract just the preload log items, do something like this:
```bash
grep ' \[PRELOAD\]' /c/Users/Jonathan/AppData/Local/OpenFin/cache/8.56.24.30/debug.log
```
(Note the leading space in the search arg, which gives better filtering of verbose logs, filtering out the `write-to-log` API calls containing [PRELOAD] made by api-decorator which are redundant.)
See sample log output in Jira [RUN-3316](https://appoji.jira.com/browse/RUN-3316).
=> RUN-3316 Log preload script progress

index.js
ℹ️ **About**
By adding `uuid` property to `desktop-icon-clicked` event we now can figure out which application is being launched
➕ **New tests**
• [System.addEventListener (desktop-icon-clicked)](https://testing-dashboard.openfin.co/#/app/tests/59c0232e7cb79f732d10c363/edit)
• [System.addEventListener (desktop-icon-clicked) T2](https://testing-dashboard.openfin.co/#/app/tests/59c011107cb79f732d10c362/edit)
✅  **Test results**
• [Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59c027917cb79f732d10c364)
• [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59c028267cb79f732d10c365)
👫 Coupled with [this PR](https://github.com/openfin/javascript-adapter/pull/339)
=> RUN-3313 added uuid property to 'desktop-icon-clicked' event

src/browser/api/application.js, src/browser/api/system.js, src/browser/api/window.js, src/browser/convert_options.js, src/browser/preload_scripts.ts, src/renderer/api-decorator.js
Default `preloads` was defined (in convert_options::`convertToElectron`) as `[]` (empty array), which was not sufficiently falsy to avoid overwriting underlying parent options.
Code in convert_options was also transforming the legacy form of the `preload` option to modern form. This is a reasonable place for it (despite the outdated name "convertToElectron" which referred to converting v5 options object for use with v6), but is was inadequately implemented as the same logic appeared in at least two other places.
Solution was to:
1. Make the default undefined rather than empty array
2. Remove the "convert" logic repetitions from other places where found
3. Ensure `convertToElectron` is called for all cases
4. Only use `preload` when defined (or convert undefined to empty array before …
=> RUN-3319 Preload scripts not injected on window.open

src/browser/api/window.js, src/browser/convert_options.js, src/shapes.ts
The default drag are really small I extended it to 4 pixels and 6 pixels on corners.
=> RUN-3049 Extend drag area for frameless window

src/browser/core_state.ts
:white_check_mark: Test Results
* [Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59c912487cb79f732d10c395)
* [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59c912ba7cb79f732d10c396)
=> RUN-3356 fixed bug that returned wrong main window in getAllWindows

src/browser/api/application.js
ℹ️ **About**
**Bug scenario:**
1. App has an invalid preload script and is already running (without its preload script, because the URL is broken and the *Core* failed to download it)
2. When launching this same app again, the *Core* tries to re-download that failed preload script again.
**Fix:** avoid preload script logic for apps that are already running
✅ **Test results**
• [Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59c948d07cb79f732d10c39c)
• [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59c949307cb79f732d10c39d)
=> RUN-3349 avoid preload script logic when not initial app launch

index.js, src/browser/api_protocol/api_handlers/event_listener.js, src/browser/api_protocol/transport_strategy/ws_strategy.ts, src/browser/connection_manager.ts, src/browser/remote_subscriptions.ts
We were missing the runtimeUuid stamp on the events raised in a multi-runtime environment.  Additionally we had scenarios where securityRealm was not taken into consideration while matching subscriptions.
[Win10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59c959b07cb79f732d10c3a9)
[Win7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59c959b07cb79f732d10c3a9)
=> RUN-3358 remote subscription loop

src/browser/log.ts, test/log.test.ts
Please see Jira [RUN-3366](https://appoji.jira.com/browse/RUN-3366) for explanation.
**[Tests](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59c96bde7cb79f732d10c3ab).**
This is another casual general improvement PR and can slip to next sprint considering this sprint has so much to merge already.
=> RUN-3366 writeToLog use toString when avail

src/browser/api/system.js, src/browser/api/window.js, src/browser/api_protocol/api_handlers/system.js
also added the ability to listen to system and application level window focused/blurred events.
Pull request for javascript-adapter: https://github.com/openfin/javascript-adapter/pull/341
:heavy_plus_sign: New Tests
* [System.getFocusedWindow](https://testing-dashboard.openfin.co/#/app/tests/59ca57c57cb79f732d10c3b6/edit)
* [System.addEventListener (window-focused)](https://testing-dashboard.openfin.co/#/app/tests/59ca4c337cb79f732d10c3b2/edit)
* [System.addEventListener (window-blurred)](https://testing-dashboard.openfin.co/#/app/tests/59ca53327cb79f732d10c3b3/edit)
* [Application.addEventListener (window-focused)](https://testing-dashboard.openfin.co/#/app/tests/59ca55c37cb79f732d10c3b4/edit)
* [Application.addEventListener (window-blurred)](https://testing-dashboard.openfin.co/#/app/tes …
=> RUN-3346 - added API to get focused window

src/browser/connection_manager.ts
Connection Manager's `isMeshEnabled` blows up when using an old .NET adapter
✅ Test Results:
• [Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59d54c617cb79f732d10c445)
• [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59d54ced7cb79f732d10c446)
=> RUN-3382 isMeshEnabled bug

src/browser/api/external_application.ts, src/browser/api_protocol/api_handlers/authorization.js, src/browser/api_protocol/api_handlers/event_listener.js
* Created types for External Application Objects
* Added isRuntimeClient function and check
* Consolidated External connections options
Please review the [External connection wiki](https://github.com/HadoukenIO/core/wiki/External-Connections) for background.
Tests:
* [Win10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59ce4ed57cb79f732d10c3f7)
* [Win7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59ce4e7e7cb79f732d10c3f6)
* Tested node-adapter with 1 expected failure
* Smoke tested .NET app and did not observe issues connecting/disconnecting
=> RUN-3363 detect external conn as runtime

src/browser/convert_options.js
Currently default backgroundColor is set to #000, so when backgroundColor in other PR will be fixed the background color of js apps will be black. Currently background color of js apps are white because "backgroundColor" of js api doesn't work correctly. First to fix "backgroundColor" functionality I need to change default background color.
=> RUN-3127 Change default backgroundColor to #FFF

src/browser/convert_options.js
Preload option being squashed by convert options.
[Win7 Tests](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59d68aea7cb79f732d10c476)
[Win 10 Tests](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59d68b4f7cb79f732d10c477)
=> RUN-3385 Preload scripts from json files were being loaded.

src/browser/api_protocol/api_handlers/middleware_entity_existence.ts
Just checking if an app is running should not toss an exception.
[tests well](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59e4f385af26a25be2ffc8e9)
[added test](https://testing-dashboard.openfin.co/#/app/tests/59e4ee38af26a25be2ffc8e2/edit)
=> RUN-3380 allow isRunning check when app is manifest created

Gruntfile.js, package.json
[js-adapter](https://github.com/HadoukenIO/js-adapter) now required via npm.
Test results:
[Win7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59e6088caf26a25be2ffc8ea)
[Win10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59e60908af26a25be2ffc8eb)
=> RUN-3442 Updated runtime-p2p to latest using npm hadouken-js-adapter

src/browser/api/system.js, src/browser/api/window.js, src/browser/api_protocol/api_handlers/window.js, src/renderer/api-decorator.js, src/shapes.ts
This is **Phase 1** of _plugin-preload separation/refactor/cleanup/fix_.
All plugin/preload tests will be written when all phases are completed.
This 1st phase:
• separates plugin/preload logic in api-decorator and window handler files
• ensures plugins are eval'ed 1st
• fixes preload script updates to final states
• [Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59e7bae7af26a25be2ffc8f9)
• [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59e7bb7baf26a25be2ffc8fa)
=> RUN-3390 (phase 1) separate plugins from preload scripts

Gruntfile.js, src/browser/api/application.js, src/browser/api/system.js, src/browser/api_protocol/api_handlers/system.js, src/browser/api_protocol/api_handlers/window.js, src/browser/core_state.ts, src/browser/plugins.ts, src/browser/preload_scripts.ts, src/browser/rvm/rvm_message_bus.ts, src/renderer/api-decorator.js, src/shapes.ts
This is **Phase 2** of _plugin-preload separation/refactor/cleanup/fix_.
All plugin/preload tests will be written when all phases are completed.
This 2nd phase:
• separates plugin logic from preload scripts logic in places that deal with plugin retrieval
• [Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59e9fea1af26a25be2ffc907)
• [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59e9feecaf26a25be2ffc908)
=> RUN-3390 (phase 2) separate plugins from preload scripts

src/browser/api/system.js, src/browser/api/window.js, src/browser/api_protocol/api_handlers/system.js, src/browser/plugins.ts
This is **Phase 3** of _plugin-preload separation/refactor/cleanup/fix_.
All plugin/preload tests will be written when all phases are completed.
This 2nd phase:
• adds plugin states (similar to preload states)
• [Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59ea5779af26a25be2ffc90e)
• [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59ea57c2af26a25be2ffc90f)
=> RUN-3390 (phase 3) separate plugins from preload scripts

index.js, src/browser/api/window.js, src/browser/api_protocol/api_handlers/window.js, src/browser/core_state.ts, src/browser/plugins.ts
ℹ️ This PR fixes the problem where consecutive apps that are started with a manifest and using the same runtime couldn't find plugins
➕ New tests:
• [window.getInfo (pluginState)](https://testing-dashboard.openfin.co/#/app/tests/59f08e56af26a25be2ffc953/edit)
• majority of the future plugins tests are all going to depend on this functionality
• [Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59f0f17daf26a25be2ffc968)
• [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59f0f1cfaf26a25be2ffc969)
=> RUN-3501 fix plugins for apps from manifest

src/browser/preload_scripts.ts
ℹ️ This PR fixes state order for successfully loaded and executed preload scripts
➕ New test:
• [window.addEventListener (preload-state-changing) (succeeded)](https://testing-dashboard.openfin.co/#/app/tests/59ee5761af26a25be2ffc922/edit)
• [Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59f23f71af26a25be2ffc975)
• [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59f23faaaf26a25be2ffc976)
=> RUN-3474 removed repetitive preload script state to keep correct order

src/renderer/api-decorator.js
Branch off https://github.com/HadoukenIO/core/pull/207.  The new changes are:
~~~javascript
-                const options = getWindowOptionsSync();
+                const identity = entityInfo.entityType === 'iframe' ? entityInfo.parent : entityInfo;
+                const options = getWindowOptionsSync(identity);
if (options.contextMenu) {
-                    const identity = getWindowIdentitySync();
~~~
Tests:
[W10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59f1fbabaf26a25be2ffc96d)
[W7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59f1fb68af26a25be2ffc96c)
=> RUN-3508: Feature/iframe context menu

src/browser/api/window.js, src/browser/cached_resource_fetcher.ts, src/modules.d.ts
@HarsimranSingh @whyn07m3 
This swaps out our custom, native backed `resourceFetcher` with the standard electron [net](https://electron.atom.io/docs/api/net/) module. We still will write the response to disk (we can eval later if keeping in memory is appropriate for all cases, I wish it was, as it is already on disc per Chrome cache rules). 
[tests well](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59f8bcf6af26a25be2ffc9b9)
=> RUN-3321 RUN-3434 move to net module

src/browser/api/notifications/subscriptions.ts, src/browser/api/window.js, src/browser/api_protocol/api_handlers/middleware_entity_existence.ts, src/browser/api_protocol/api_handlers/window.js, src/modules.d.ts, src/renderer/api-decorator.js
ℹ️ This PR prevents execution of preload scripts and plugin modules in notifications (including queue counter)
➕ New tests:
• [Notification (no preload scripts)](https://testing-dashboard.openfin.co/#/app/tests/59f8ce3caf26a25be2ffc9bb/edit)
• [Notification (no plugin modules)](https://testing-dashboard.openfin.co/#/app/tests/59fb2517af26a25be2ffc9e9/edit)
• [Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59fb24ccaf26a25be2ffc9e8)
• [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59fb2533af26a25be2ffc9ea)
=> RUN-3489 prevent preload scripts & plugin modules in notifications

src/renderer/api-decorator.js
ℹ️ This PR ensures final "preload-scripts-state-changed" event is emitted when at least one required preload script failed to load
➕ New test: [window.addEventListener (preload-scripts-state-changed) (load-failed)](https://testing-dashboard.openfin.co/#/app/tests/59ef3a4faf26a25be2ffc925/edit)
• [Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a00e6e61573627ee4384254)
• [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a00e74b1573627ee4384255)
=> RUN-3475 fix emission of final state for load-failed preload scripts

src/browser/api/window.js, src/browser/convert_options.js, src/browser/plugins.ts, src/shapes.ts
Changed `plugin` to `plugins` (manifest)
• [Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a134f2d9a4b9e06a9723a58)
• [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a134ecb9a4b9e06a9723a57)
=> RUN-3443 changed 'plugin' to 'plugins'

src/browser/cached_resource_fetcher.ts
Tests:
[W10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a15ac689a4b9e06a9723a77)
[W7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a15ac1d9a4b9e06a9723a76)
=> RUN-3617: ENOENT from cachedFetch 8.56.26 2nd round

src/renderer/api-decorator.js
ℹ️ Shows preload scripts' and plugins' eval errors in console
➕ New tests:
• [Preload scripts: print eval error to console](https://testing-dashboard.openfin.co/#/app/tests/5a1c2c629a4b9e06a9723a8b/edit)
• [Plugins: print eval error to console](https://testing-dashboard.openfin.co/#/app/tests/5a1c6fb29a4b9e06a9723a8e/edit)
• [Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a1c828f9a4b9e06a9723a94)
• [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a1c82df9a4b9e06a9723a95)
=> RUN-3598 shows preload scripts' and plugins' eval errors in console

src/browser/cached_resource_fetcher.ts
RUN-3662 Fixed issue where auth events on resource fetcher were not handled. (#264)
=> Merge 8.56.26/staging into develop

src/browser/api_protocol/api_handlers/event_listener.js, src/browser/api_protocol/api_handlers/mesh_middleware.ts, src/browser/remote_subscriptions.ts
Second phase implements the system events that need to be aggregated together from other runtimes.  There are timing issues that need to be fixed that result in not receiving application created or started events on a new runtime startup:   [JIRA for event timing](https://appoji.jira.com/browse/RUN-3654) 
[JS-Adapter Tests](https://github.com/HadoukenIO/js-adapter/pull/66)
• [Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a1ddb039a4b9e06a9723aa6)
• [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a1ddb4c9a4b9e06a9723aa7)
=> RUN-3328 (phase 2) multi-runtime mesh system events

src/browser/api/application.js, src/browser/api/system.js, src/browser/api/window.js, src/browser/api_protocol/api_handlers/application.js, src/browser/api_protocol/api_handlers/system.js, src/browser/cached_resource_fetcher.ts, src/browser/plugins.ts, src/browser/preload_scripts.ts, src/renderer/api-decorator.js, src/shapes.ts
⚠️ Sorry about one massive change in a single PR. When I was removing in-memory caching, there was so much to change and later fix, that I just ended up fully refactoring. Splitting this into multiple phases would be hard and time consuming.
On a positive side, I believe that this change, although massive, removes **a lot** of complexity (51%) around preload scripts and will be pleasure to work with for possible future bugs and edge cases.
Forgive me for my _big changes_ sins
ℹ️ This PR:
1. removes in-memory caching for preload scripts
2. refactors and cleans up preload scripts logic
3. fixes correct event order for "preload-scripts-state-changing" when window.reloads
4. handles re-downloading preload scripts with Wenjun's PR
➕ New test: [Preload scripts: window.reload …
=> RUN-3563 RUN-3564 RUN-3565 RUN-3536 preload scripts refactor/cleanup/fix

src/browser/rvm/rvm_message_bus.ts, src/renderer/api-decorator.js, src/shapes.ts
ℹ️ Since plugins moved from `optional` to `mandatory` option, we are adding the same change for preload scripts. _We will still support `optional` option for preload scripts though..._
👫 Coupled with [this javascript-adapter PR](https://github.com/openfin/javascript-adapter/pull/362)
➕ Tests: 
1. [new Window (preloadScripts) (multiple, missing optional)](https://testing-dashboard.openfin.co/#/app/tests/59b929a83d90dd51ca4f101c/edit)
2. [new Window (preloadScripts) (multiple, missing required)](https://testing-dashboard.openfin.co/#/app/tests/59ee0116af26a25be2ffc910/edit)
3. [new Window (preloadScripts) (multiple, missing default)](https://testing-dashboard.openfin.co/#/app/tests/59ee03d9af26a25be2ffc911/edit)
✅ Test results: [Windows …
=> RUN-3444 replaces 'optional' option with 'mandatory' for preload scripts

src/browser/api/application.js, src/browser/api_protocol/api_handlers/application.js, src/browser/rvm/rvm_message_bus.ts
https://appoji.jira.com/browse/RUN-3588
This PR is for the new "registerUser" API that will replace the currently unused registerCustomData (see: https://github.com/openfin/Internal-Wiki/wiki/Custom-License-Registration)
Tests:
[W10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a25cfba299179466481952a)
[W7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a25cf3e2991794664819529)
[New Test](https://testing-dashboard.openfin.co/#/app/tests/5a25ce482991794664819528/edit) (I have more tests that need to be made public once the new RVM goes stable)
Related javascript-adapter PR: https://github.com/openfin/javascript-adapter/pull/365
=> RUN-3588 add support for registerUser API

index.js
check if globalShortcut was destroyed before calling unregisterAll
✅ Test Result:
[Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a3bef896f202a5432b79f82)
[Runtime PR](https://github.com/openfin/runtime/pull/780)
=> RUN-3452 check if globalShortcut was destroyed

package.json
Newer version of runtime-p2p has a few issues, would not affect any feature in .27 but will need fixing for .28.
Test results:
[Win7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a3d56f36f202a5432b79f87)
[Win10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a3d577f6f202a5432b79f88)
=> Revert back to an older version of the p2p package untill bugs are fixed.

src/browser/convert_options.js
experimental application option for shimming `--disable-init-reload` per app (process)
```
'experimental': {
'disableInitialReload': false,
'v2Api': false
},
```
Relates to https://github.com/openfin/runtime/pull/783
main.js already has the correct spelling
https://github.com/HadoukenIO/core/blob/develop/src/renderer/main.js#L48
=> RUN-3727 experimental application option

src/browser/api/application.js, src/browser/api/window.js
check if window object was destroyed before invoking the callback
✅ Test Results:
[Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a4d99efbd581266877d663c)
[Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a4d9a72bd581266877d663d)
=> RUN-3657 fixed bug that causes exception 

src/browser/api_protocol/api_handlers/interappbus.js
IAB subscription listeners were added but not removed on unload event, added code to remove them on unload event.
:white_check_mark: Test Results:
[Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a308b7b6f202a5432b79f33)
[Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a308c0b6f202a5432b79f34)
=> RUN-3455 remove listeners on unload

src/browser/navigation_validation.ts
validates the navigation rules only when parent app is still running
:white_check_mark: Test Results:
[Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a3929256f202a5432b79f68)
[Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a3929a26f202a5432b79f69)
=> RUN-3620: fixed bug that tries to access unavailable application properties

src/browser/api/notifications/subscriptions.ts
close event was dispatched before notification was closed, thus missing click events, fixed the bug by dispatching close event after notification window was closed.
:white_check_mark: Test Result:
[Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a329bef6f202a5432b79f46)
[Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a329c6b6f202a5432b79f47)
=> RUN-2393 dispatch "close" event after window was closed.

src/browser/api/interappbus.js, src/browser/api_protocol/api_handlers/interappbus.js
[Javascript-Adapter PR](https://github.com/openfin/javascript-adapter/pull/379)
Per [RUN-3756](https://appoji.jira.com/browse/RUN-3756), was not getting any success callbacks on a 2nd IAB subscription to a given UUID (including wildcard) and topic. When fixing that, saw [this issue (RUN-3761)](https://appoji.jira.com/browse/RUN-3761) where we are also not getting the 2nd subscribe listener from IAB.addSubscribeListener so this fixes that as well since the fix for it would be a better fix than what I had for RUN-3756.  With this PR, we are letting the core handle multiple subscriptions to the same UUID & topic from a given subscriber, which allows the core to emit to any subscribe/unsubscribe listeners out there. 
[Win7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a5e …
=> RUN-3756 - Send all IAB subscriptions to core to get success ack & emit to IAB.add(un)SubscribeListener

npm-shrinkwrap.json
Fixes this issue https://github.com/HadoukenIO/core/issues/252
Steps to solution:
1) Confirm that I'm on NodeJS v6.9.0 (the recommended version in the README.md)
2) `grunt clean && rm -rf node_modules/ && rm npm-shrinkwrap.json`
3) `npm install && npm shrinkwrap --dev`
Tests for core built w/ 6.9.0
[Win 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a568fa9bd581266877d668d)
[Win 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a568f0ebd581266877d668c)
Tests for core built w/ 7.10.1
[Win 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a56914fbd581266877d6690)
[Win 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a5690a2bd581266877d668f)
Test for core build w/ 8.9.1
[Win …
=> RUN-3753 update npm-shrinkwrap.json so it can work for Node versions 6+

src/browser/bounds_changed_state_tracker.js
Per [this JIRA](https://appoji.jira.com/browse/RUN-3672), all windows in a group were changing position based on the top-left corner (top side or left side) resizing.  I.e. if window 2 was to the right of window 1 and a user made window 1 larger by clicking&dragging the top-left corner, window 2 would still move to the left.  This PR makes it so that only windows that are on the correct side are moved by resizing.  
There are still issues here but I think they are beyond the scope of this ticket.  If the window is simultaneously moved and changed in size the other windows in the group will not move correctly.  However, this cannot be done by the user (requires a setBounds API call) so developers can easily make this a 2-step process (moveby, then resizeby).  Also, if there are multiple …
=> RUN-3672 Resizing a window in a group

index.js, src/browser/api/system.js, src/browser/api_protocol/api_handlers/system.js, src/renderer/api-decorator.js, src/renderer/main.js
This PR [and its sibling PR](https://github.com/openfin/runtime/pull/804) move the launch of the renderer's crash reporter from core's api-decorator to the runtime.
**Test results**: [Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a675e583f32861e82b77c63), [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a675f0f3f32861e82b77c64)
=> RUN-3690 moved renderer crash reporter launch to runtime

index.js, src/browser/api/application.js, src/browser/convert_options.js, src/renderer/api-decorator.js
This PR is fixing below two issues:
1. When launched for the first time, the application is not receiving the deep linking parameters.
2. Second launch and beyond, which triggers the run-requested method, do receive the arguments. However, they are only received as one string in the event.userAppConfigArgs key. The design docs states it should be able to use event.userAppConfigArgs.parameterName.
Test results: [Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a6f73e33f32861e82b77cb4) [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a6f74c33f32861e82b77cb5)
Currently there are no auto tests specifically for deep linking. It requires a manual test.
=> RUN-3748 deeplinking parameters not passed

src/browser/api/system.js, src/modules.d.ts
Tests
[W10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a721b733f32861e82b77cf2)
[W7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a721a683f32861e82b77cf1)
New fields added to host specs:
aeroGlassEnabled:true
screenSaver:false  // Windows only
still need to update js API docs for System.getHostSpecs
=> RUN-3796 Expose info on screen saver and aero theme

src/browser/convert_options.js, src/renderer/api-decorator.js, src/renderer/node-less.js
Experimental feature behind an application flag.
```
'experimental': {
'node': true,
},
```
Related to https://github.com/openfin/runtime/pull/819
=> RUN-3776 - (Experimental) Remove API dependence of Node

src/browser/api/window.js, src/browser/rvm/rvm_message_bus.ts, src/browser/rvm/utils.ts, src/shapes.ts
[JIRA](https://appoji.jira.com/browse/RUN-3772)
As part of log management, we want to send console.log, console.info, console.error, etc. messages from the core to the RVM, and the RVM will write them to separate files (to avoid writing logs from every application to the same debug.log). Sending a message from the core to the RVM on every console log is too hard on the browser process (and sends a lot of messages to the RVM), so instead we store all the messages in a queue. Every time a message is pushed to an empty queue, we set a timer to flush it in 10s.
Tests:
[Win7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a7487ad3f32861e82b77d08)
[Win10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a74881c3f32861e82b77d09)
=> RUN 3772 queue up console.* messages from the app and send them to the RVM

src/browser/api/window.js
**About**
When a renderer crashes, while being subscribed to its own `"close-requested"` and `"show-requested"` events, it will prevent the core from shutting down.
This PRs unsubscribes listeners for these events on renderer crashes
**New tests**:
• [Window.addEventListener (close-requested) (renderer crash)](https://testing-dashboard.openfin.co/#/app/tests/5a81dfb883591b524677a774/edit)
• [Window.addEventListener (show-requested) (renderer crash)](https://testing-dashboard.openfin.co/#/app/tests/5a81e1c883591b524677a775/edit)
**Test results**
&#10003; [Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a81e8856a994a57faa5c894)
&#10003; [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a81e9076a994a57faa5c896)
=> RUN-3782 unsubscribe blocking events when renderer crashes

src/renderer/node-less.js
[W10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a85fd536a994a57faa5c900)
[W7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a85fc686a994a57faa5c8f[f)
[Runtime](https://github.com/openfin/runtime/pull/838)
=> RUN-3829 fix getVersion for node-less

src/renderer/node-less.js
Tests
[W10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a95cff06a994a57faa5c98f)
[W7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a95cf0c6a994a57faa5c98e)
[Runtime](https://github.com/openfin/runtime/pull/859)
=> RUN-3885: node-less WebFrame zoom

src/browser/cached_resource_fetcher.ts
The issue is with global makingCacheDir and makingAppDir.  If one request sets it to true, another request may come in before makeDirectory returns.  
makeDirectory checks for EEXIST already, so removing makingCacheDir and makingAppDir.
To test check for EEXIST, just add same URL as preload scripts multiple times.
[W10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a945c926a994a57faa5c97b)
[W7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a945baf6a994a57faa5c97a)
[New Test](https://testing-dashboard.openfin.co/#/app/tests/5a9593ff6a994a57faa5c985/edit)
=> RUN-3866: sync issue with cachedFetch

src/renderer/api-decorator.js, src/renderer/main.js
This is ***one of the few steps*** of async plugins implementation.
Small changes for easier code review & consumption.
**About**
Adding the new runtime argument `--async-plugins` behind which the rest of the new functionality will hide. Without this new flag, plugins will function the old synchronous way, like preload scripts.
**Test results**
✅ [Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a945e596a994a57faa5c97c)
✅ [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a945f596a994a57faa5c97d)
=> RUN-3848 added a flag for future async plugins loading

src/browser/api/system.js, src/browser/api/window.js, src/browser/api_protocol/api_handlers/system.js, src/browser/plugins.ts
This is ***one of the few steps*** of async plugins implementation.
Small changes for easier code review & consumption.
**About**
This PR adds ability to retrieve one specific plugin at a time, on-demand and without evaluating it.
**Test results**
✅ [Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a95b6a66a994a57faa5c98a)
✅ [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a95b7816a994a57faa5c98b)
=> RUN-3883 single plugin retrieval

README.md, package.json, src/renderer/main.js
v2 adapter now is acquired the same way the v1 adapter is acquired.
Additionally exposed deploy and build tasks as npm scripts so they can be launched without a global grunt install. 
Test results:
[Win 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a95d8d76a994a57faa5c992)
[Win 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a95d9c36a994a57faa5c993)
=> RUN-3837 Added no asar search paths to js-adapter, exposed grunt task as as npm scripts

src/renderer/api-decorator.js
Consumed by the adapters new and old. 
[Win 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a9713016a994a57faa5c99a)
[Win 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a97154f6a994a57faa5c99b)
=> RUN-3839 Removed the usage of the browser side API to generate GUIDs, replaced it with the render side getGUID API

src/renderer/node-less.js
Tests:
[W10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a9daba76a994a57faa5c9dc)
[W7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a9daad66a994a57faa5c9db)
[Runtime](https://github.com/openfin/runtime/pull/864)
=> RUN-3901: Feature/nodeless opener success callback called

src/browser/api/window.js
When an application crashes (main window, so not x-orig child) set the running state of the app as false
[tests well](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5aa2b3496a994a57faa5ca4f)
[test added](https://testing-dashboard.openfin.co/#/app/tests/5aa180f26a994a57faa5ca38/)
=> RUN-3819 killed running false

src/browser/api_protocol/api_handlers/service_middleware.ts
Bug fix to add name to ack key so that child windows don't overwrite each other's messages (OK for name to be undefined)
=> RUN-3812 - Services Core - add name to Ack key

src/browser/api/system.js, src/browser/api_protocol/api_handlers/system.js, src/renderer/api-decorator.js
From `api-decorator` we were sending out a series of ready/initialization events using sync calls (though they happened from within an async load event). This change preserves the order and moves the entire set of calls to a single api call that fans out browser side to raise each event. 
Tests well
[Win 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5aa7421c6a994a57faa5ca64)
[Win 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5aa742df6a994a57faa5ca65)
=> RUN-3880 move the sync ready events from renderer to browser process

npm-shrinkwrap.json, package.json
Removed runtime-p2p from npm-shrinkwrap.json since optionalDependencies don't seem to play well with shrinkwrapping.
Also changed openfin-sign to use the GitHub URL syntax over ssh.
=> RUN-3895 remove optional dependencies from npm-shrinkwrap to fix build

src/browser/api/service.ts, src/browser/api_protocol/api_handlers/service_middleware.ts
Added a services event namespace.   Had previously been leveraging application and system namespaces.  See javascript-adapter PR [here](https://github.com/openfin/javascript-adapter/pull/409)
Reworked tests included in tests below:
[Win7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5ab29e4a6a994a57faa5cae3)
[Win10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5ab29f7a6a994a57faa5cae4)
=> RUN-3821 - Services Event Namespace

src/browser/api/interappbus.js, src/browser/api_protocol/api_handlers/interappbus.js
with current design, the adapter should do filtering and dispatching of the messages, so on core side, it could simply blast all the messages out to the adapter.
✅ Test Result:
[Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5ab349a46a994a57faa5caf3)
[Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5ab34a746a994a57faa5caf4)
=> RUN-3960 fixed issue with duplicated listener registration.

src/browser/api/application.js
Fixed issue where if you closed a window before fin.desktop.main would throw an Object Destroyed error.
Tests: 
[Win10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5ac3e4854ecc2a37d5a483de)
[Win7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5ac3e3c54ecc2a37d5a483dd)
=> RUN-3974 Object Destroyed error on on pre-main close.

src/browser/api/window.js
This PR fixed a function name change error in getSnapshot. (V9)
Test Results:
[Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5accc5724ecc2a37d5a4843f)
[Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5accbecf4ecc2a37d5a4843d)
=> RUN-3966 getSnapshot threw not function js error in V9

src/renderer/api-decorator.js
We support a subset of [features as described by MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/open), features not supported are either not relevant to OpenFin windows or non standard. The list of features we support are:
* [height](https://developer.mozilla.org/en-US/docs/Web/API/Window/open#height)
* [width](https://developer.mozilla.org/en-US/docs/Web/API/Window/open#width)
* [top](https://developer.mozilla.org/en-US/docs/Web/API/Window/open#top)
* [left](https://developer.mozilla.org/en-US/docs/Web/API/Window/open#left)
* [centerscreen](https://developer.mozilla.org/en-US/docs/Web/API/Window/open#centerscreen)
* [resizable](https://developer.mozilla.org/en-US/docs/Web/API/Window/open#resizable)
* [chrome](https://developer.mozilla.org/en-US/docs/Web/API/Window/open#chrom …
=> Feature/RUN-3958 window.open with options

src/browser/api/application.js, src/browser/api_protocol/api_handlers/authorization.js
[JIRA](https://appoji.jira.com/browse/RUN-4008)
We want to send the parent app's config url to the RVM on the app-started event, since it will be helpful for us to tie together different records when looking at licensing data.
Tests:
[W7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5acbcc434ecc2a37d5a48439)
[W10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5acbcdac4ecc2a37d5a4843a)
I investigated the test failures and they appear to be flaky tests, unrelated to my changes. I reran each failure individually and observed the following:
* Window.navigateBack passes when I reran it with my asar
* Window.getSnapshot, Window.getSnapshot T2, and Notification.close all fail on regular canary, without my asar
Not sure if those are known issues or not
=> RUN-4008: Send parent config url to RVM on app started event

src/browser/api/application.js, src/browser/rvm/rvm_message_bus.ts
RVM now has the ability to request an app to be closed, this is related to Service life cycle.
Works relates to changes from @patpao on the RVM end.
Test results:
[Win 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5adfa2504ecc2a37d5a48506)
[Win 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5adfa2fa4ecc2a37d5a48508)
=> RVM-621 Added the ability to close applications at the request of the RVM.

src/renderer/api-decorator.js
in situations where the render process limit hits we cannot trust the frame info from the core, we need to ensure we are the main frame from the renderer instead.
Tests:
[Win 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5ae3721f4ecc2a37d5a48561)
[Win 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5ae3728e4ecc2a37d5a48562)
=> RUN-4048 in situations where the render process limit hits we cannot trust the frame info from the core (dealing with that in a seperate issue).

release.json, src/browser/api/system.js
Tests
[W10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5af9e8214ecc2a37d5a48657)
[W7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5af9e6b74ecc2a37d5a48655)
[New test](https://testing-dashboard.openfin.co/#/app/tests/5afad8c64ecc2a37d5a4866c/edit)
=> RUN-4118: add cachePath to getRuntimeInfo

src/browser/api/window.js
This change decreases memory leaks by approximately 12%
✅ [Windows 7 automated tests](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5afaf4b34ecc2a37d5a4866d)
✅ [Windows 10 automated tests](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5afaf6524ecc2a37d5a4866e)
=> RUN-4120 clean up all webContents' listeners on "close"

src/browser/api/window.js, src/shapes.ts
This change decreases memory leaks by approximately 13%
✅ [Windows 7 automated tests](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5afb1c4a4ecc2a37d5a48679)
✅ [Windows 10 automated tests](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5afb1eb34ecc2a37d5a4867a)
=> RUN-4120 clean up all browserWindow's listeners on "closed"

src/browser/api/window.js, src/browser/core_state.ts
Edit: removed incorrect language around frame options 
Per customer request, we are adding state ('normal', 'minimized', 'maximized') and isShowing (boolean) to the System.getAllWindows call.  
[Testrunner Test:](https://testing-dashboard.openfin.co/#/app/tests/5af9dd2b4ecc2a37d5a48649/edit) that tests new payload
[Win7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5af9de7f4ecc2a37d5a4864c)
[Win10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5af9dfb74ecc2a37d5a4864d)
=> RUN-4059 - Additional payload added to System.getAllWindows

src/browser/rvm/rvm_message_bus.ts, src/browser/rvm/utils.ts, src/browser/transports/wm_copydata.ts
[JIRA](https://appoji.jira.com/browse/RUN-4104)
Also, if the payload is to be masked, it's not written to the log.
[Runtime PR](https://github.com/openfin/runtime/pull/996)
[Test results](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5afb140f4ecc2a37d5a48677)
=> RUN-4104: Add ability to mask RVM payloads; do so for application-log

src/browser/bounds_changed_state_tracker.js
Emit the `begin-user-bounds-changing` event for use in layouts / snap-and-dock.  
See [javascript-adapter](TBD) PR for documentation.
[Win7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5aff1c294ecc2a37d5a486df)
[Win10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5aff1db84ecc2a37d5a486e0)
=> RUN-4143 - Emit Begin User Bounds Changing

src/browser/api/system.js
Propagated window created, crashed, closed to system level eventing for layouts.  Should we do any other window or application events? 
[Win7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b060fbd4ecc2a37d5a48723)
[Win10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b0610f44ecc2a37d5a48724)
New Testrunner tests System events:
[window-created](https://testing-dashboard.openfin.co/#/app/tests/5aff47ee4ecc2a37d5a486ed/edit)
[window-closed](https://testing-dashboard.openfin.co/#/app/tests/5aff48984ecc2a37d5a486ee/edit)
[window-crashed](https://testing-dashboard.openfin.co/#/app/tests/5b060c7b4ecc2a37d5a48722/edit)
=> RUN-4159 - Propagate events to system

src/browser/api/service.ts, src/browser/api_protocol/api_handlers/service.ts, src/browser/api_protocol/api_handlers/service_middleware.ts, src/browser/bounds_changed_state_tracker.js, src/shapes.ts
Did a slight refactor of services to:
- make multi-runtime work
- make it so a single app could both register as a service and connect to other services as a client
- make future changes to the handshake easier
Instead of using the UUID to store/lookup the service (on both core & adapters), we now use a "channelId".  ChannelId is currently just uuid/${number} where 'number' is just an incrementing number.  This new property will future changes to the handshake and the way the channel is stored in the core / adapters a bit easier.  The adapters are also now sending back the serviceIdentity (with channelID property) along with every message after the connection.  
This change should retain backward compatibility.  
Required javacript-adapter and js-adapter changes as well.  Ran the tests …
=> RUN-4068 - Multi runtime services and slight refactor

src/browser/api/window.js, src/browser/api_protocol/api_handlers/window.js
Making sure that on a entity close/disconnect event we enable the window **frame**
Tests:
[Win10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b32687954b21953031f3632)
[Win7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b3267c154b21953031f3631)
=> RUN-4065 disable frame unhook

src/browser/remote_subscriptions.ts
Fixed issue where remote subscriptions `unSubscriptions`map was being cleared on disconnect but not recreated on runtime re-connect.
The subscription object is initialized once in [addRemoteSubscription](https://github.com/HadoukenIO/core/blob/develop/src/browser/remote_subscriptions.ts#L80) and cleaned on disconnects on [unSubscribe](https://github.com/HadoukenIO/core/blob/develop/src/browser/remote_subscriptions.ts#L212). This does not take into consideration the fact that this subscription will be re-enabled if the identity is found in a new runtime or if it is a system subscription via [applyAllRemoteSubscriptions](https://github.com/HadoukenIO/core/blob/develop/src/browser/remote_subscriptions.ts#L226)
When we [applyRemoteSubscription](https://github.com/HadoukenIO/core/blob/develop/s …
=> unsubscriptions.get is not a function exception

src/browser/convert_options.js
One small fix (duplicate `spellCheck` key). Tests are all clean
[win 10 x64](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b4379e254b21953031f36a9)
[Windows 7 (64-bit)](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b4378af54b21953031f36a7)
[Megatron W7 Runtime 32](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b4378cc54b21953031f36a8)
=> 8.56.30/staging into 9.61.32/staging

src/browser/session.ts, src/modules.d.ts
To Emit `session-changed` event on MAC_OS, **subscribeNotification** the screen lock and unlock event on using **systemPreferences** interface.
Just like the WIN_OS implementation which utilizes a hidden window to listen **WM_WTSSESSION_CHANGE** messages.
=> RUN-4150: Emit session-changed event on MAC_OS

Gruntfile.js, npm-shrinkwrap.json, package.json
ℹ️ This PR cleans up core's dependencies and so greatly decreases the size of the core.
Here's the breakdown of the main changes:
module name | before | after | change
--- | --- | --- | ---
hadouken-js-adapter | 1.5MB | 620KB | cleaned up
minimist | 64KB | 8KB | cleaned up
options | 12KB | 12KB | no change
q | 164KB | 0 | removed
request | 5.15MB | 0 | removed
rx | 6.94MB | 144KB | cleaned up
ultron | 16KB | 16KB | no change
underscore | 128KB | 20KB | cleaned up
ws | 172KB | 172KB | no change
This decreased the size of `app.asar` **from 13.4MB to 1.75MB (-87%)**
✅ [Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b31297954b21953031f3623)
✅ [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b312acd54b21953 …
=> RUN-4195 cleaned up core's dependencies

src/browser/api/application.js, src/browser/core_state.ts
This used to get the root ancestors manifest information, and now gets the closest parent (i.e. its own if launched from manifest, if not recursively check if parent was and return the first manifest.) . I also added initialOptions for when an app is not launched from manifest.  
I added a UUID check to [this test](https://testing-dashboard.openfin.co/#/app/tests/5b118f15f2f2e22fa4b7c266/edit) to ensure it is the correct manifest.
[PR for change to javascript-adapter docs](https://github.com/openfin/javascript-adapter/pull/447)
[Win7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b3b85ed54b21953031f366b)
[Win10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b3b875354b21953031f366e)
[redo 1 failed win7 …
=> RUN-4032 - Fix for Application getInfo

Gruntfile.js
ℹ️ **About**
This PR changes the way Mocha reports back test results.
It was too verbose, we only really care about failed tests. Let's change it.
**Before** (99+ lines, both succeeded and failed tests are shown)
**Now** (2 lines, only failed tests are shown)
=> changed mocha test reporting

test/errors.test.ts, test/global_hotkey.tests.ts, test/log.test.ts, test/peer_connection_manager.tests.ts, test/rvm_message_bus.test.ts
ℹ️ **About**
This PR prevents `mockery` module to pollute (when running tests) standard out with noise about whether it's mocking or not mocking modules (screenshot below)
✅ [Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b3e857054b21953031f3694)
✅ [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b3e863f54b21953031f3695)
=> Prevent mockery noise

src/browser/core_state.ts
This is an interim fix to getAppAncestor, it would return undefined if the parent application was in another runtime.  Now, it will return the app before it.  
I created a [JIRA](https://appoji.jira.com/browse/RUN-4241) to investigate and fix this more permanently as I dont think we would always want to get the app ancestor if it is in another runtime (see JIRA).
[Win7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b3b867c54b21953031f366c)
[Win10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b3b879c54b21953031f366f)
=> RUN-4241 - Fix undefined return when parent is in another runtime

src/browser/api/notifications/subscriptions.ts
This PR fixed notification ondismiss not working issue.
Tests: [Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b460a4054b21953031f36e3)   [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b460b4b54b21953031f36e6)
[Manual Test added](https://github.com/openfin/test_apps/pull/30)
=> RUN-4211 Fixed notification ondismiss not working issue

src/browser/api/window.js
Exposing internal `will-close` event publicly as `closing`.
[Win 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b48049954b21953031f3711)
[Win 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b4805b754b21953031f3712)
=> Made 'will-close' eveent public as 'closing'

index.js, src/common/errors.ts
ℹ️ **About**
This PR enables *safe-errors* mode by default, with an option to opt out by providing `--disable-safe-errors` runtime flag
🚥 **Automated test results**
✅ [Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b46329254b21953031f36e9)
✅ [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b46335454b21953031f36ea)
=> RUN-4102 enable safe errors mode by default

src/browser/subscription_manager.ts, test/global_hotkey.tests.ts
Fixes the core error when restarting an application listening to 'application-created'.
Tests: [7](https://testing-dashboard.open) [10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b50f34354b21953031f375c)
=> RUN-4266 cannot-destructure-uuid-undefined

src/browser/core_state.ts
The actual error from this ticket came from the destructuring of openfinWindow here. To be sure that we are catching every instance of this possible error (was also seen in a ticket from 8.56.30.*, not related to the missing event cleanup from other PR) we should add some protection here.
(please note that TS cleaned up some un-used variables in the PR I cherry-picked)
Tests against staging
[Win7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b51f78f54b21953031f376b)
[Win10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b51f88554b21953031f376d)
=> RUN-4266 - Type protection in elipc

index.js
Because the value of `userData` changes on OS X, we simply re-check the value
of it, rather than setting it once and forgetting it.
=> RUN-4310: Fix log rotation and process file deletion on OS X

src/browser/api/window.js
By moving window tear down to the will-close event we will reduce the time between objects leaving memory and core state being updated.
[Win7 x64](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b51fd1e54b21953031f376f)
[Win7 x32](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b51fd3454b21953031f3770)
[Win10 x64](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b51fdc454b21953031f3771)
[Win10 x32](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b51fe1c54b21953031f3772)
=> RUN-4269: Moved window teardown from 'closed' to 'will-close'

index.js
Tests
[W10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b4fafd454b21953031f374f)
[W7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b4faf3b54b21953031f374e)
=> RUN-4238: not override remote-debugging-port from ChromeDriver

src/browser/api_protocol/api_handlers/application.js
[Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b563e9c54b21953031f37ba)
[Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b563c5754b21953031f37b8)
=> RUN-4322 getApplicationGroups should only return necessary properties

Gruntfile.js
Adding new dependencies to the core _(with nested dependencies)_ was problematic. The developer was forced to explicitly add all nested dependencies at the top-level of the project to avoid errors at runtime. 
This PR leverages NPM to query immediate and nested production dependencies ensuring all required modules are present in the final output asar/folder
**NOTE** : The _js-adapter_ includes `@types` as a production dependency.
```
hadouken-js-adapter
minimist
options
rx
ultron
underscore
ws
```
```
@types
hadouken-js-adapter
minimist
options
rx
ultron
underscore
ws
```
https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b5783fb54b21953031f37dc
https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b577cb354b21953031f37da
=> RUN-4329 Nested dependencies are not packaged

npm-shrinkwrap.json, package.json
Bump to js adapter. Pulls in may fixes and is needed for the service -> iab cut over
[Windows 10 (64-bit)](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b5b971854b21953031f3841) all pass
[Windows 7 (64-bit)](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b5b961e54b21953031f3840) all pass
=> bumped js-adapter to 0.34.1-alpha.2

src/browser/convert_options.js, src/renderer/main.js, src/renderer/node-less.js
This moves the experimental api.iframe api injection config into
startup_app.api.iframe. The idea of the outer api key is to provide
the option to manage injection to windows or apps in the future.
As is, you can now decide if iframes get the openfin api or no based
on their domain (cross origin or not). As is, this option is not
inherited.
=> RUN-4332 move iframe out of experimental

src/browser/api/window.js
Removed the second emit.
Tests:
[Win 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b5f546754b21953031f385e)
[Win 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b5f557a54b21953031f385f)
=> RUN-4346 window-end-load event is being emitted twice

src/renderer/main.js, src/renderer/node-less.js
@StevenEBarbaro @HarsimranSingh @whyn07m3 
This fixes the memory leak, it was the remote module returning an object, even thought the render side goes away, the remote `_cache` was holding it in memory. 
~Tests in flight~
Tests well:
[Win 7 32 bit](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b64c12554b21953031f38c9)
[Win 7 64 bit](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b64c0ea54b21953031f38c8)
=> RUN-4356 return string from remote apiWithOptions call

src/browser/api/window.js, src/browser/api_protocol/api_handlers/window.ts, src/browser/convert_options.js, src/shapes.ts
see https://github.com/openfin/Internal-Wiki/issues/40
requires https://github.com/openfin/runtime/pull/1080 to be merged
A general note: the aspect ratio is only enforced when the window is resized. For example, if `startup_app.aspectRatio` is given as `1`, windows may initially be shown with a different aspect ratio, because the window has not yet been resized. I think this behaviour is correct, as otherwise unintuitive collisions might occur with other window options.
=> RUN-3525: Add aspect ratio as a window option

assets/error.html, index.js, src/browser/api/application.js, src/browser/api/window.js, src/common/errors.ts, src/shapes.ts
ℹ️ **About**
This PR:
1. Improves our custom error dialog
2. Uses our custom non-blocking error dialog to display app initialization errors (screenshot below)
3. Uses our custom non-blocking error dialog to notify users about renderer crashes (screenshot below)
➕ 3 new manual tests [here](https://github.com/openfin/test_apps/pull/32)
🚥 **Automated test results**
✅ [Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b59de3854b21953031f380d)
✅ [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b59df4054b21953031f380e)
🖼 **Screenshots**
1. App initialization
2. App initialization custom message (our `customWindowAlert` app config flag)
3. Renderer crash
=> RUN-3911 normalize errors

src/browser/api/channel.ts, src/browser/api_protocol/api_handlers/event_listener.js, src/browser/remote_subscriptions.ts, src/common/route.ts
This PR does two things that turned out to be intertwined:  
1.) Makes channels work correctly in multi-runtime
- fixed some eventing stuff for channels, particularly remote subscriptions
- put pending channels on renderer side
* If channel does not yet exist, nack back to renderer with specific message.  Renderer then listens for connection event and will resend the connect message -where it can be routed to correct runtime via normal mesh middleware.  
* better handles lifecycle of request
* better to implement multi-runtime channel connection with eventing / existing middleware
2.) Make connection to a channel more flexible - can now use uuid only / identity (uuid and name) / and/or channelName (new construct)
- still need to use UUID for multi-runtime to work but channelName only …
=> RUN-4342 Multi-Runtime channels

Gruntfile.js, tsconfig.json
* Moved our typescript target to 2017
* Noticed our tests and gruntfile were making their way into packaged asar.
Tests: 
[Win10 x32](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b6def7054b21953031f3943)
[Win 10 x64](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b6def2d54b21953031f3942)
[Win7 x32](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b6dee1b54b21953031f3941)
[Win7 x64](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b6dee0d54b21953031f3940)
=> A few build changes:

src/browser/api_protocol/api_handlers/system.ts
Fixed object destructuring in `raiseEvent`
🚥 **Automated test results**
[Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b74872c6107b45e6d1eba03)
[Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b74883e6107b45e6d1eba04)
=> RUN-4392 fixed raiseEvent

src/browser/runtime_p2p/peer_connection_manager.ts
ℹ️ **About**
Believe it or not, this 2-character change took me 3-4 days and Pierre 2-3 days of investigation. This is a very nasty timing issue, hard to reproduce on command, but been showing up consistently lately in our test results. Apparently, the number of failures can exceed the number of runtimes in the map during another runtime shutdown.
👍 However, on the plus side, this long investigation also yielded **positive results**:
1. Discovered and fixed an improper promise resolution in the test runner
2. Found 7 automated tests had uncaught exceptions
3. Found 4 tests that purposely crash apps and windows linger around throughout the whole test suite, which is okay, but not ideal
4. Came up with an idea or two on how to improve test runner's logging
5. And last but not least, fixed …
=> RUN-4397 fixed createFromManifest timing problem

src/browser/api/system.js
This simply returns the SHA256 hash of the MAC address.
Note that incorrect behaviour in Windows is ignored; see RUN-4451.
=> RUN-2986: Implement getDeviceId() for non-Windows systems

src/browser/transports/unix_domain_socket.ts
This fixes (most, but evidently not all) multi-runtime OS X tests.
It turns out that within the Node adapter test framework, there's a bunch of
layers that result losing track of the PATH environment variable.
Instead of trying to find out where, we could simply ignore the non-existent
PATH and call the binaries that we know are there.
This assumes a Unix system that's not _too_ far out of whack.
#1storypoint
=> RUN-4400: Call Unix binaries with full path

src/browser/api/window.js
The runtime was hardcoded to prevent _INFO_ and _WARN_ console messages from being written into the _debug.log_
This change
1. Relies on removing the hardcoding from the runtime [PR](https://github.com/openfin/runtime/pull/1135)
2. Allows the core to designate what gets written to the debug.log
[Test Results](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b859bcb6107b45e6d1ebbaf)
=> RUN-4466 Core controls console messages in the debug.log

src/browser/api_protocol/transport_strategy/elipc_strategy.ts, src/browser/convert_options.js, src/renderer/api-decorator.js
IFrames will now get their own names by default allowing them to
act as discrete endpoints on the IAB. If a user wants to opt into
the old frameConnect style behavior it can be opted into via
api.frame.enableDepricatedSharedName being set to true.
This removes the need for `--frameStragety=frames` and it will now
be ignored. 
Requires [this](https://github.com/openfin/javascript-adapter/pull/490) adapter pr
Tests well
[win 7 64](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b88019f6107b45e6d1ebbdf)
[win 10 32](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b88035d6107b45e6d1ebbe1)
[win 10 64](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b8803246107b45e6d1ebbe0)
=> RUN-4202 RUN-3435 Name iframes as default

src/browser/api_protocol/api_handlers/system.ts
Tests:
[Win 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b996f736107b45e6d1ebc7d)
[Win 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b9970f86107b45e6d1ebc7e)
=> RUN-4566 - getAppAssetInfo always returns the error: "Cannot set property 'srcUrl' of undefined"

index.js
ain't gonna work w/o https://github.com/openfin/runtime/pull/1162
this includes:
- using process.buildFlags.enableChromium
- moving app.isGroupPolicyBuild() to process.buildFlags.groupPolicy
=> RUN-4564: Use process object for build flag logs

src/browser/api/window.js, src/common/errors.ts
ℹ️ Minor fixes + limit active number of our custom error boxes to **10**
➕ New test (manual test apps PR): [Qty limit for custom error dialogs](https://github.com/openfin/test_apps/pull/46)
🚥 Automated tests results:
✅ [Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b9bd7cf6107b45e6d1ebc98) (same as vanilla)
✅ [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b9bd8d86107b45e6d1ebc99) (same as vanilla)
=> Run 4360 some fixes for our custom error boxes

Gruntfile.js
No underlying NodeJS change, just bumping this number.
✅ [Win 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b9c21b06107b45e6d1ebcbe)
✅ [Win 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b9c20796107b45e6d1ebcbc)
=> Bump electron rebuild to use 2.0.7

src/browser/transports/unix_domain_socket.ts
There's two sets:
`O` := open file descriptors, found by lsof | grep
`A` := all file descriptors, found by ls
Ideally, `O` and `A` are identical, but sockets may become abandoned via
scenarios like runtime crashes. In this case, |`O`| < |`A`|, and the /tmp folder
can fill up with useless sockets.
This PR deletes everything in `A` - `O`.
=> RUN-4533: Clean up abandoned file descriptors upon socket creation

index.js
Before:
```
~/Library/Application Support/OpenFin/<encoded url><optional security realm>/
```
After:
```
~/Library/Application Support/OpenFin/cache/<encoded url>/<optional security realm>/<version>/
```
=> RUN-4639 fix mac cache path to be more like windows

src/browser/api/file_download.ts
Differentiate between original file name and user chosen name on download events
Test Results:
https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5babc93ccb360141a7dfcf89
=> RUN-4646 Download events with user-chosen name

index.js, src/browser/convert_options.js
Removing experimental flag requirement for the download listener API.
Test results: 
[Win 7](https://testing-dashboard.openfin.co/#/app/sessions)
[Win 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5bad3a1ecb360141a7dfcfa6)
=> Removed the need to specify any experimental flag in order to use the file download API

Gruntfile.js, npm-shrinkwrap.json, package.json
to enable v10 build on MAC.
To eliminate the warning for node-abi version complaint from bootstrap [using new electronVersion](https://github.com/electron/electron-rebuild/issues/251), add the latest 2.4.5 version to devDependencies.
=> RUN-4460: Fix/v10/version

src/browser/api/window.js, src/browser/api_protocol/api_handlers/window.ts
ℹ️ **About**
This and related PRs add support for taking snapshots of an area of a window.
🔗 All linked PRs
1\. [core PR](https://github.com/HadoukenIO/core/pull/561)
2\. [javascript-adapter PR](https://github.com/openfin/javascript-adapter/pull/500)
3\. [js-adapter PR](https://github.com/HadoukenIO/js-adapter/pull/188)
➕ **New automated tests**
1\. [window.getSnapshot (specified area)](https://testing-dashboard.openfin.co/#/app/tests/5ba1497ad6d66a0ddf8e7253/edit)
2\. [window.getSnapshot (specified area) (V2 API)](https://testing-dashboard.openfin.co/#/app/tests/5baa700ecb360141a7dfcf5f/edit)
🚥 **Test results**
✅ [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5baa75bbcb360141a7dfcf65)
✅ Node test results
=> RUN-2315 added support for taking a snapshot of an area in a window

src/browser/api_protocol/api_handlers/application.js
Nack when .run is called instead of hanging.
Tests:
[Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5bb294afcb360141a7dfcfde)
[Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5bb2936acb360141a7dfcfdb)
=> RUN-4671 Fail on duplicate run calls

src/browser/remote_subscriptions.ts
This function was leaking remote subscriptions.
✅ Automated tests
[Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5bc73fcfcb360141a7dfd0ca)
[Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5bc74108cb360141a7dfd0cb)
=> RUN-4636 fix for subscribeToAllRuntimes

src/browser/bounds_changed_state_tracker.ts, src/modules.d.ts
1: for full screen window, set to normal mode first.
2: No need to restore cached bounds on mac cause we hasn't [store the window's bounds before max or fullscreen](https://github.com/openfin/runtime/blob/d8f3a2aa275bf085d12716f89ea86573dd7d0bba/atom/browser/native_window_views.h#L393).
=> RUN-4525: refine grouped window move on MAC

index.js
For enable_chromium, if otherInstanceRunning is true, app.quit tries to shut down Chromium components that are not initialized yet and can cause crash of 2nd instance.  app.exit just exits.
Tests
[W10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5bc78e22cb360141a7dfd0de)
[W8](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5bc78c90cb360141a7dfd0db)
=> RUN-4654: calling app.exit during delegated launch

src/browser/runtime_p2p/peer_connection_manager.ts
Fixes an issue where a resolveUuid call would hang while port discovery was happening
[Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5bc755d3cb360141a7dfd0d1)
[Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5bc754fecb360141a7dfd0d0)
=> RUN-4708 Fixed hanging resolve-uuid

src/browser/port_discovery.ts, src/browser/transports/chromium_ipc.ts
Fixes issue where port discovery via chromeIPC (named pipe) was periodically failing due to garbage collection cleaning up the chromeIPCclient before the message was sent out.  We are now saving the client as a property on the instance (that can be overwritten if need be by a new chromeIPCclient).  
Also added try / catch protection around port discovery broadcast.
[Win7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5bcf6982cb360141a7dfd136)
[Win10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5bcf6b23cb360141a7dfd137)
=> RUN-4718 - Port Discovery Fix

src/browser/api/window.js, src/renderer/api-decorator.js
This PR is fixing window zoom issue for HSBC. (for .36)
Tests:
[Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5bd0d0d1cb360141a7dfd14b)
[Windos 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5bd0d210cb360141a7dfd14c)
=> RUN-4715 Fix window has incorrect zoom level issue when reopen

src/browser/api_protocol/api_handlers/mesh_middleware.ts, src/browser/api_protocol/transport_strategy/ack.ts
Changes multi-runtime error messages from `RuntimeError: Error: **error message**` to `RuntimeError: **error message**`
Test results
[Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5bb38008cb360141a7dfcfef) (Failed one test which passed multiple times otherwise)
[Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5bb3811fcb360141a7dfcff0)
=> RUN-4670/Forward error message rather than error

src/browser/port_discovery.ts, src/browser/transports/chromium_ipc.ts
Cherry-picked this PR from a1cdf5923ccd967f924d57f89137078511d43f96:
Fixes issue where port discovery via chromeIPC (named pipe) was periodically failing due to garbage collection cleaning up the chromeIPCclient before the message was sent out. We are now saving the client as a property on the instance (that can be overwritten if need be by a new chromeIPCclient).
Also added try / catch protection around port discovery broadcast.
=> RUN-4718 - Port Discovery Fix (#592)

src/browser/api_protocol/api_handlers/event_listener.js, src/browser/of_events.ts, src/browser/remote_subscriptions.ts, src/common/route.ts
ℹ️This PR ensures we don't miss multi-runtime events during another runtime's starts-up
⛓ Paired with this [js-adapter PR](https://github.com/HadoukenIO/js-adapter/pull/196)
➕[New test: Multi-runtime missed events](https://testing-dashboard.openfin.co/#/app/tests/5bae247ecb360141a7dfcfab/edit)
✅ **Automated test results**
[Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5bbcf827cb360141a7dfd041)
[Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5bbcfea3cb360141a7dfd042)
=> RUN-3654 don't miss multi-runtime events

src/browser/api/window.js, src/browser/convert_options.js, src/browser/core_state.ts, src/common/main.ts, src/renderer/api-decorator.js, src/shapes.ts
[Runtime](https://github.com/openfin/runtime/pull/1218)
Tests
[W7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5bcf3595cb360141a7dfd133)
[W10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5bcf3705cb360141a7dfd134)
[Test with enable_chromium build of Runtime](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5bcfc4bdcb360141a7dfd144)
Tests of context menu failed because contextMenu has been replaced with contextMenuSettings
Also, contextMenuSettings can not be updated in enable_chromium build of Runtime, for now.
=> RUN-4717: Support devtools and reload as window options

src/browser/bounds_changed_state_tracker.ts, src/browser/rectangle.ts, src/browser/utils.ts, test/rectangle.ts
There are a few things that this PR does, but mostly it is a precursor to making group resizing a deferred-bounds transaction by starting to tease out and isolate the logic that handles the positioning from the logic that decides how and when to move it. 
The three changes to behavior that this makes are:
*  Windows will now only resize if they are within 5px of each other. Currently, for example, a vertical resize will resize any window resting on that `x` value no matter where it is on the screen
* Windows now, when they are within the 5 px threshold and are a candidate for a grouped resize will take the value of the resizing edge exactly, meaning that they snap to the resizing edge and stick there.
* When a window that is being resized reaches its minimum size it will be pushed in the …
=>  RUN-4690 only resize inside threshold plus move rectangle math 

src/browser/api/application.js
[Tests](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5bd3b961cb360141a7dfd19b)
[Runtime](https://github.com/openfin/runtime/pull/1224)
Chrome pages need the original window.alert, confirm, prompt.
=> RUN-4480: no API injection for Chrome pages

src/browser/api_protocol/api_handlers/mesh_middleware.ts, src/browser/api_protocol/transport_strategy/elipc_strategy.ts, src/browser/api_protocol/transport_strategy/ws_strategy.ts
Fixed multi-runtime channels bug where channels calls that get aggregated across runtimes did not work when there was a runtime version alive that is prior to the version in which the call had been implemented.
Also added nack on unimplemented API calls.
[Win7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5bdc6feacb360141a7dfd1d8)
[Win10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5bdc711acb360141a7dfd1d9)
=> RUN-4733 - Multi-Runtime Channels Bug

src/browser/api_protocol/api_handlers/grouped_window_moves.ts
also undoes the auto commit of the js-adapter
=> removed unnecessary async

src/browser/disabled_frame_group_tracker.ts
Let's wait for confirmation from the layouts team, but we were applying the offset twice and therefore failing when delta was 0.
=> only apply offset once on api moves

src/browser/api/window.js, src/browser/rvm/utils.ts, src/shapes.ts
If `startup_app.appLogFlushInterval` is defined, it'll be used as a flush
interval for application logs, with the value being interpreted as
milliseconds. Note that flushing can still occur earlier if a buffer of 1
MB is hit (maybe we want to also make that magic value configurable?).
If it's not defined, the existing flush interval of ten seconds is used.
=> RVM-733: User-configurable flush interval for app logs

src/browser/api/channel.ts, src/browser/api_protocol/api_handlers/channel.ts
Added calls to destroy or disconnect from a channel and fixed some lifecycle eventing around a channel participant restarting or navigating (destroying context where channel class was created).  
[js-adapter PR](https://github.com/HadoukenIO/js-adapter/pull/203)
New Testrunner tests:
[test1](https://testing-dashboard.openfin.co/#/app/tests/5be1bffecb360141a7dfd22f/edit)
[test2](https://testing-dashboard.openfin.co/#/app/tests/5be09f96cb360141a7dfd1fc/edit)
[test3](https://testing-dashboard.openfin.co/#/app/tests/5be0a3d9cb360141a7dfd200/edit)
[test4](https://testing-dashboard.openfin.co/#/app/tests/5be0a5bfcb360141a7dfd201/edit)
[test5](https://testing-dashboard.openfin.co/#/app/tests/5be0a0facb360141a7dfd1fe/edit)
[test6](https://testing-dashboard.openfin.co/#/app/tests/5be1ac71cb360141a7 …
=> RUN-4677 - Channel lifecycle

Gruntfile.js, package.json
ℹ️ Changes:
1. `npm run build` now points to the correct Grunt task
2. Grunt's _js-adapter_ task will work faster as it will only webpack for browser (core takes care of server js-adapter code)
⛓ Requires [these js-adapter changes](https://github.com/HadoukenIO/js-adapter/pull/208)
=> RUN-4758 build fix

src/browser/api_protocol/api_handlers/application.js
The current implementation just receives an Ack or a Nack depending on whether the log was uploaded. Now we pass along a payload with the logId for the log that was uploaded.
To run:
```
app = fin.desktop.Application.getCurrent();
app.sendApplicationLog((info) => {
console.log('logId', info.logId);
}, (err) => {
console.log(err);
});
```
=> RUN-4834 Updated Ack to send logId in a data payload.

index.js
Tests
[W7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5c115d98cb360141a7dfd690)
[W10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5c115f43cb360141a7dfd693)
Performance, measured with Date.now()
with copy:  8 milliseconds
without copy:  0 milliseconds
Tested migrations:  8.56.30.55  -> 9.61.37.42,  9.61.36.36 -> 9.61.37.42
=> RUN-4846: cookie migration for enable_chromium

index.js, src/browser/api/application.js, src/browser/transports/unix_domain_socket.ts
Although there is no standard when close main window on mac,
it's petty reasonable to keep runtime alive after main window is closed (all-window-closed),
and then create the same main window when click on dock icon(just like chrome did on mac).
The tests works well on windows.
=> RUN-4819: mac main window close

src/browser/api/window.js, src/browser/api_protocol/api_handlers/window.ts
Test:
[Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5c111daccb360141a7dfd66f)
=> RUN-4829 naming change from 'frame' to 'userMovement'

src/browser/of_events.ts, src/browser/remote_subscriptions.ts, src/modules.d.ts, test/electron.ts, test/event-propagation.ts
⚠️ It requires [runtime changes](https://github.com/openfin/runtime/pull/1281)
ℹ️ This PR makes subscriptions use our new custom native-backed function for timing. This ensures that multiple runtimes are on the same timeline (using system time) as we've discovered some issues with javascript's `Date` class.
=>  RUN-4786 event subscription improvement (Phase 2)

src/browser/api_protocol/api_handlers/window.ts, src/browser/bounds_changed_state_tracker.ts, src/browser/window_groups.ts, src/browser/window_groups_runtime_proxy.ts
Disabled frame group is now on by default,  the `use-legacy-window-groups` flag will be there to opt out.
Manual tests: OK
Auto Tests running.
=> RUN-4816 disabled frame group now on by default

src/browser/of_events.ts, src/browser/remote_subscriptions.ts
Don't re-propagate events from an external runtime to avoid double propagation
=> RUN-4855 fixed multi-runtime propagation

src/browser/external_window_event_adapter.js
ExternalWindows will now propagate 'will-close' for cleanup/API eventing.  The normal teardown/cleanup does occur in both the core and native
[Test Results: Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5c180ed5cb360141a7dfd72b)
[Test Results: Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5c181018cb360141a7dfd72d)
=> RUN-4856 fix(external-windows): Emitting 'close' events for ExternalWindows

Gruntfile.js, npm-shrinkwrap.json, package.json, src/browser/api/notifications/observable_sequences.ts, src/browser/api/notifications/subscriptions.ts, src/browser/api/window.js, src/modules.d.ts
just what the doctor ordered (get it? because `rx`? ha)
implicit here is that an internet connection exists when building the core (because rxjs doesn't distribute a .min.js file, instead relying on [unpkg](https://unpkg.com) to do it)
this was followed, which was mostly painless: https://github.com/ReactiveX/rxjs/blob/4ffbbe56ab6c5ba46497c0154d83d27f882476fb/MIGRATION.md
=> RUN-4893 fix(v11 core): upgrade rx to rxjs

index.js, src/browser/api/application.js, src/browser/api_protocol/api_handlers/application.js
This adds a call to 'destroy-application' to the core to remove an app from core-state if it is not running. This is a prerequisite to [this PR](https://github.com/HadoukenIO/js-adapter/pull/230).
=> RUN-4644 Replace Application "create" + "run" calls with "start" and "close" with "quit"

src/browser/api/application.js, src/browser/cached_resource_fetcher.ts, src/browser/convert_options.js
This PR is to read a manifest config file from RVM local cache folder. It will solve the issue that Runtime can't reach app config behind a firewall. 
Tests:
[Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5c3cc159cb360141a7dfd8ff)
[Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5c3cbce3cb360141a7dfd8fd)
=> RUN-3465 Read manifest file from rvm local cache folder

src/browser/disabled_frame_group_tracker.ts, src/browser/rectangle.ts, test/rectangle.ts, tsconfig.json
When a window resizes and is part of a group, the resize will now be
propagated through the group impacting windows that are "downstream"
of the resizing window in both the x and y directions. Resize events
along one axis or the other should now only impact windows that are
reachable through the window graph on that axis.
There are still cases where with this change I am seeing broken edges
on occation, in talks with the native team it may be due to scaling
(using dip or not). This exists currently and can be addressed in the
future if need be.
- [X ] PR title starts with the JIRA ticket [pull request process](https://github.com/openfin/Internal-Wiki/wiki/Pull-Request-Process)
- [X ] PR release notes describe the change in a way relevant to app-developers
Window resizes in a group now …
=> RUN-4813 RUN-4814 RUN-4815 Propagate resizes through the window graph

src/browser/api/application.js
Supporting the "createFromManifest" call on mac/linux.
Enables support for createFromManifest on mac/linux.
Notes:
=> RUN-4943 createFromManifest support for mac/linux

src/browser/api/native_window.ts, src/browser/api/window.js, src/browser/utils.ts, src/modules.d.ts, src/shapes.ts
This is the first step to adding native window support. This represents the abstraction of actions taken on a browser window to allow for external windows to be layered in later. On its own it will not add any functionality. 
@whyn07m3 please have a look and if you could pick up on any PR feedback it would be much appreciated. 
[tests well](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5c59e786cb360141a7dfdb0b)
n/a
=> NWI initial intgration

src/browser/window_groups_runtime_proxy.ts
Missing a `group-changed` event handler for multi runtime window groups.
When the reason equals `merge` and the targetWindow was our proxy window we would take no action.
=> Merge not handled for Target window

src/browser/api/external_window.ts, src/modules.d.ts
This prepares and decouples the core from any native refactor to decouple ExterrnalWindows from BrowserWindows.
Constructing instances of this module implicitly sets `releaseOnClose` behavior to ExternalWindows
Runtime changes are required: https://github.com/openfin/runtime/pull/1368
=> RUN-5003 task: Use runtime's ExternalWindow mock

src/renderer/api-decorator.js, src/renderer/main.js
This PR is to check the license key field in the app manifest and also does validation that the length of license key should be 36 characters. If the license key is missing or the length is wrong, we will display a warning message in the console.
=> RUN-4958 Warning in console if no license key is included

src/browser/utils.ts
This reverts unneeded changes to the clipBounds function that resulted in api calls moving windows when asked to shrink them past their minimums.
Notes: Resolved an issue where resize calls would move windows when trying to resize past constraints.
=> RUN-4947 Undo clamp changes

src/browser/api/window.js, src/browser/convert_options.js
Bug fix.
**Bug description:**
If using `waitForPageLoad:false` combined with `saveWindowState:true` the window would show briefly in the default location before being restored to the saveWindowState.
**Bug cause:**
By passing the [`show` property](https://electronjs.org/docs/api/browser-window#showing-window-gracefully), the window was showing before the `windowPositioningObserver` got chance to act.
**Bug fix:**
No longer relying on the `show` property, the core now controls window show through and through. additionally `windowPositioningObserver` will now short Circuit if `waitForPageLoad:false` is passed.
Fixed issue where using `waitForPageLoad:false` combined with `saveWindowState:true` the window would show briefly in the default location before being restored to the …
=> RUN-4956 wait for page load autoshow

src/renderer/api-decorator.js
This PR creates an assumption of `waitForPageLoad: false` when creating a child window through `window.open()`
Creates a behavior more similar to a browser, where a window opens before fetching and drawing parsing its DOM.
=> RUN-5014 This was from aziz512, on a branch not named develop

src/browser/api/window.js, src/browser/rectangle.ts
This pr makes sure that size constraints are accurate when updating the window frame option.
Previously these constraints would be off by the width of the window frame.
This would cause issues for grouping.
Notes: Fixes an issue where a window's size constraints would be inaccurate if the window frame option was toggled
=> RUN-5032 Size constraints update when changing frame

src/browser/api/window.js, src/common/main.ts
Window options updates will now be extending previous options, instead of replacing them.
This was causing an exception in the core for this specific scenario:
1. Create a new window with `autoShow: false` and `frame: false`
2. Partially update window options (like in the example below)
3. Show the window
4. Error box shown for the exception thrown in the core
1. Window options before updating: `{ ..., resizeRegion: { ..., sides: { top: true, ... }}}`
2. `wnd.updateOptions({ resizeRegion: { sides: { top: false } } })`
3. Window options after updating: `{ resizeRegion: { sides: { top: false } } }` 
1. Window options before updating: `{ ..., resizeRegion: { ..., sides: { top: true, ... }}}`
2. `wnd.updateOptions({ resizeRegion: { sides: { top: false } } })`
3. Window options after updating: …
=> RUN-5006 deep merge of window options

index.js
Write info about `not-responding` and `responding` events to the log when in diagnostics mode.
https://appoji.jira.com/browse/RUN-5077
Notes: Added `not-responding` and `responding` events to logging when in diagnostics mode.
=> RUN-5077: Write not-responsive events to log

src/browser/api/window.js
**Added a 'options-changed' event to window after window.updateOptions is done.** 
The payload contains a diff array containing prev and new values for all changed options.
Would appreciate if you could also take a look at the [dashboard test](https://testing-dashboard.openfin.co/#/app/tests/5c9a5c6acb360141a7dfdec4/edit)
Related [js adapter PR](https://github.com/HadoukenIO/js-adapter/pull/259)
Notes: Added a 'options-changed' event to window after window.updateOptions is done.
=> RUN-5069 Add window options updated event (take #2)

src/browser/api_protocol/api_handlers/authorization.js
Releases the lock on a uuid when the corresponding process disconnec
JIRA ticket: https://appoji.jira.com/browse/RUN-5134
Test PR in js-adapter: https://github.com/HadoukenIO/js-adapter/pull/268
Notes: Resolved issue where locked uuid's were not released on termination of an external connection.
=> RUN-5134: Release uuid's on websocket disconnect

src/browser/window_groups_runtime_proxy.ts
Proxy windows will now update their _options object once their proxied window's options change.
Would appreciate feedback on the [dashboard test](https://testing-dashboard.openfin.co/#/app/tests/5c9e80c0cb360141a7dfdf3d/edit)
This PR branched out of pull/754 and uses the 'options-changed' event introduced in it.
The PR is Dependent on [this js-adapter PR](https://github.com/HadoukenIO/js-adapter/pull/259)
=> RUN-5084 - Proxy Window _options are not updated when the original window is.

src/browser/api/window.js
- fixed a bug that caused contextMenu to not update
- added contextMenu to getOptions payload
=> RUN-5218 [Regression 10.66.41.*] Updating contextMenu window option has no effect

src/browser/api/system.js
System.getRuntimeInfo now includes the command line argument used to start the Runtime in the form of an Object
=> RUN-5223 added the args object to the getRuntimeInfo call

src/renderer/main.js
This PR is to fix the false warning message when a license key is valid.
=> RUN-5242 Show a false warning message when there is a valid license key

src/browser/core_state.ts, src/renderer/main.js, src/renderer/node-less.js
Changes api injection to rely on webcontents id rather than browserWindow id
Notes: N/a legwork for browserView support
=> RUN-5189 Inject based on webcontents Id

src/browser/api/system.js, src/browser/api_protocol/api_handlers/api_policy_processor.ts, src/browser/api_protocol/api_handlers/system.ts
Adds the ability to get the json blob that is associated with a service. As written you can get any configuration you'd like provided you know it's name. We can handle discovery and if these should be private to the service itself in later efforts.
A note about testing: currently it is not feasible to round-trip test a custom version of the runtime and rvm simultaneously. This change requires just that. It also requires setting custom a custom desktop owner settings file compounding the testing difficulties. For now, lets please just use our brains in review as best we can :)
@pjbroadbent  
Linked to [this js adapter pr](https://github.com/HadoukenIO/js-adapter/pull/275)
Note: this requires [this](https://github.com/openfin/openfinrvm/commit/57cc300a3989feb6e5324d53b8f13059f68b5328) RVM …
=> RUN-5112 Add the ability to get the desktop owner settings for services

src/browser/api/window.js
Duplicate of https://github.com/HadoukenIO/core/pull/781, but targeting 10.66.41/staging.
Jira ticket: https://appoji.jira.com/browse/RUN-5200
When user closes a window before it's safe, hide the window, but wait for the DOM `load` event is fired to actually close the window.
SIGNIFICANT CAVEAT: This works for most sites I tested, but NOT for cnn.com. I suspect iframe shenanigans, or possibly something caused by their very slow js event handlers. Further investigation needed
Notes:
=> RUN-5200: Don't close window till content loaded - 10.66.41/staging

src/browser/api/window.js
https://appoji.jira.com/browse/RUN-5263
Hide window when user attempts to close before initial load is finished. Prevent it from flashing when it finishes loading.
- x ] PR description included and stakeholders cc'd
Notes:
=> RUN-5200: Hide window on close-requested

src/browser/transports/unix_domain_socket.ts
Fixes timing issue probably introduced in .41 with two apps starting at the same time
Notes: na
=> RUN-5314/added pid to unix_dgram name

src/browser/api/external_window.ts
* Making sure external window's events conform with window's events payload.
note: there are still some mismatches, they're commented in the code.
[JIRA](https://appoji.jira.com/browse/RUN-5201)
Related to [js-adapter pr](https://github.com/HadoukenIO/js-adapter/pull/289)
=> RUN-5201: NWI: add docs tutorials for new API / events (partial) 

src/browser/transports/injection_bus.ts
Jira ticket: https://appoji.jira.com/browse/RUN-5270
Include the core instance's mesh uuid as `senderID` on send calls, instead of using a hard-coded value.
=> RUN-5270: Append meshUuis to injection bus msgs

src/browser/api/external_window.ts
This PR adds missing payload properties for external window's "disabled-movement-bounds-changed" event.
N/A
=> RUN-5238 added missing info to "disabled-movement-bounds-changed"

src/browser/session.ts
Evidently an offset of 0 and byteLength of 1 were defaults if not given,
but in this new version of Node 12.0.0, it's now an error.
Not an error in Node 10.11.0:
https://github.com/electron/node/blob/f0153d018bc33a05764427f4804d6a0b693ececb/lib/internal/buffer.js#L235
An error in Node 12.0.0:
https://github.com/electron/node/blob/842a35fbac5c29e8bb095fe3716375232ee0d0ce/lib/internal/buffer.js#L235
=> Fix readIntLE() call

src/browser/api/external_window.ts, src/browser/api/system.js, src/browser/utils.ts, src/shapes.ts
This PR changes **some** of external window info objects returned to the client.
The changes affect the following API/events (these were unnecessarily getting full info object / extra info).
Other APIs / events return only needed info, similar in shape to regular OpenFin windows.
- `fin.System.getAllExternalWindows`
- `"external-window-closed"`
- `"external-window-created"`
- `"external-window-hidden"`
- `"external-window-shown"`
Info object **before**:
```
alwaysOnTop: false,
bounds: {
height: 265,
width: 319,
x: 150,
y: 350,
},
className: 'Notepad',
dpi: 96,
dpiAwareness: -1,
focused: false,
id: '0x00040658',
maximized: false,
minimized: false,
name: 'Notepad',
process: {
imageName: 'C:\Windows\System32\notepad.exe',
injected: false,
pid: 5924,
},
title: 'Untitled - Notepad',
uuid: …
```
=> RUN-5265 cleaned up external window info object

src/browser/api/external_window.ts, src/electron.d.ts
This fixes external window's "blurred" event.
Prior to these changes, we relied on the injection to help us trigger "blurred" event. But, because "blur" from the injection appears to be broken and not wanting to rely on the injection, here we will use "focus" win event hook with some state tracking to implement "blurred" event for native windows.
N/A
=> RUN-5235 fixed "blurred" event for external windows

src/browser/animations.js, src/browser/api/system.js, src/browser/api/webcontents.ts, src/browser/api/window.js, src/browser/api_protocol/api_handlers/clipboard.ts, src/browser/external_window_event_adapter.ts, src/browser/navigation_validation.ts, src/browser/session.ts, src/browser/transports/chromium_ipc.ts, src/electron.d.ts, src/modules.d.ts, src/shapes.ts
Additional backport work:
Fixed problems found by using latest definition of electron, namely getZoomLevel of WebContents is sync function now. This was already fixed on of-master during intake.
=> Backport ts resync to v13 branch.

src/browser/api/window.js, src/browser/api_protocol/api_handlers/window.ts
This PR modifies Windowing APIs that resize windows. If a Windowing API call attempts to resize a window outside of its `maxHeight`/`maxWidth`/`minHeight`/`minWidth` constraints, the function will nack. 
Affected functions:
`Window.animate`
`Window.resizeBy`
`Window.resizeTo`
`Window.setBounds`
**This PR will change the behavior of these API calls. Previously, the windows would resize up to their constraints, and the functions would ack. Now, we prevent all resizing, and nack instead**
The following tests will need to have a Max Version set @whyn07m3 :
https://testing-dashboard.openfin.co/#/app/tests/55897c432517bd926e4a257b/edit
https://testing-dashboard.openfin.co/#/app/tests/55897c432517bd926e4a257c/edit
The following tests will need to have a Min Version set (once this PR is merged …
=> [RUN-5033] Windowing API calls nack if size constraints would be violated

src/browser/api_protocol/api_handlers/authorization.js
Jira ticket: https://appoji.jira.com/browse/RUN-5350
@wenjunche was seeing some runtime issues when runtime uuids were prematurely released. This change should fix.
=> RUN-5350: Free app uuids on disconnect, not runtime

src/browser/api_protocol/api_handlers/api_protocol_base.ts, src/browser/api_protocol/transport_strategy/api_transport_base.ts, src/browser/api_protocol/transport_strategy/elipc_strategy.ts, src/browser/core_state.ts, src/modules.d.ts, src/shapes.ts
Use webcontents id to resolve sender identity so browser view can subscribe to iab/events
Notes: N/A underlying work for browser view
=> RUN-5358 Use webcontents id in ELIPC Strategy

src/browser/api/external_window.ts
Jira: https://appoji.jira.com/browse/RUN-5364
This error will be thrown on any action that attempts to interact with a nonexistent ExternalWindow, not just `wrap` calls.
This includes both windows that used to exist, but have been closed since wrapping, and windows that never existed in the first place. So input welcome if anyone has an error message that might more fully communicate the situation without becoming overly verbose.
=> RUN-5364: Update error to describe more cases

src/browser/api/external_window.ts, src/browser/api_protocol/api_handlers/grouped_window_moves.ts, src/browser/window_groups.ts
This PR fixes the regression where windows wouldn't join or merge a group in the multi-runtime environment.
N/A
- [Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5d136e2bcb360141a7dfe74e) (1 failed test unrelated to this change)
- [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5d136e4ccb360141a7dfe74f) (5 failed tests, unrelated to this change)
=> RUN-5380 fixes window grouping regression

src/browser/convert_options.js
Goal of this task is to add possibility to launch Electron's unittests located in directory electron/spec on OpenFin's application. It will allow us to check if our chages break their apis or cause any regressions. These tests - in the future - could also be used as integration criteria for our tasks/bugfixes.
=> RUN-5363: Enable Electron's unittests

src/browser/api/external_window.ts, src/browser/api_protocol/api_handlers/external_window.ts
This change is for enabling external window's frame when all its requestors are gone.
N/A
=> RUN-5233 disabled external window frame

src/renderer/api-decorator.js
Adds a `performance-report` event which provides timing and navigation data from Performance API.
Tests:
https://testing-dashboard.openfin.co/#/app/tests/5d167362cb360141a7dfe78e/edit
https://testing-dashboard.openfin.co/#/app/tests/5d16860dcb360141a7dfe78f/edit
https://testing-dashboard.openfin.co/#/app/tests/5d166f6fcb360141a7dfe78d/edit
Developers can subscribe to  `performance-report` event to benchmark window creation and conveniently collect data to analyze and track performance of their applications.
@rdepena @datamadic
=> Add performance-report event

src/browser/api/window.js
This PR fixes the bug where if you use `enableFrame()` before using `disableFrame()`, the count of the disabled frame requestors would be wrong and that would cause the frame to be enabled while there is still at least one requestor alive.
Fixed a bug relating to disabled frames and incorrect number of requestors
=> RUN-5349 bug fix for disabled frames with alive requestors

src/browser/bounds_changed_state_tracker.ts, src/browser/rectangle.ts, test/rectangle.ts
When RTv10 windows are tabbed by the Layout Service they can't be resized vertically from the top or the bottom.  The bottom is a bug that will affect not only tabbed windows.  There is a bug where when there are 3+ windows, the move will not get propagated to all of the windows.  This has been replicated with two windows on top of each other (same bounds), then a third window on any side of the window.  Try to resize either of the windows with identical bounds - in the direction towards or away from the third window and it will fail to resize.  
This is related to this [JIRA](https://appoji.jira.com/browse/RUN-5348) but only fixes half the issue.
- [ x ] PR description included and stakeholders cc'd
- [ x ] `npm test` passes
- [ x ] automated tests are added (see unit test in PR)
- [ x ] …
=> RUN-5392 - group resize bugfix

src/browser/api/window.js
Without it context menu will be destroyed after first launch of
javascript's garbage collector even when menu is still displayed.
Notes:
=> RUN-5420: Keep reference to created context menu

Gruntfile.js
This version wasn't bumped correctly and as a result unix-dgram
wasn't fetched during building.
Notes:
=> RUN-5451: Fixed version of electron

src/browser/api/channel.ts, src/browser/core_state.ts, src/shapes.ts
The PR fixes a bug where if both channel provider creation and client connection happen in two different iframes of the same window, the provider promise resolves but the client promise never does.
@rdepena @datamadic @dhamberlin 
This allows to create channels from iframe entities.
=> Fix Channels API iFrame bug

src/browser/api/window.js
Without it context menu will be destroyed after first launch of
javascript's garbage collector even when menu is still displayed.
This is a backport of a fix from of-master.
=> RUN-5420: Keep reference to created context menu (#870)

src/browser/api/window.js
Window.setbounds was throwing an error out in restorewindowstate as it was changed to require a callback function in v43.  Due to the error, it was not going through the windowstate and zoomlevel restoration.
And another one:
Using browserview.show instead of window.show goes around our show-requested logic that is in window.show.  In order to have the show-requested logic work correctly, use Window.show in window startup.  
- [ x ] PR description included and stakeholders cc'd
- [  ] `npm test` passes
- [  ] automated tests are [changed or added](https://testing-dashboard.openfin.co/#/app/dashboard)
- [ x ] PR title starts with the JIRA ticket [pull request process](https://github.com/openfin/Internal-Wiki/wiki/Pull-Request-Process)
=> RUN-5461  - v43 regressions fix

src/browser/api_protocol/api_handlers/external_window.ts, src/browser/api_protocol/api_handlers/window.ts
As per https://appoji.jira.com/browse/RUN-5470 , we currently don't support grouping External Windows since some of the group move behaviors are currently undefined
Test: https://testing-dashboard.openfin.co/#/app/tests/5d48431aa18af715bfcc7146/edit
Docs Update: https://github.com/HadoukenIO/js-adapter/pull/313
Notes: Joining groups with external windows is currently not supported
@rdepena @datamadic
=> RUN-5470 Join Group should Nack if given an "Native Window"

src/browser/api/application.js
When an app has preload scripts there is a chance for a timing issue on app creation / run.  The app is not set to running in corestate until after the downloading of the preload scripts.  In the app.create call, we check for app.isRunning, which synchronously will be true if there are no preload scripts.  If preloads need to be downloaded, however, it creates an async call where another app.create call can jump in. 
Example flow for bug:
1.) App1 create, and run.  main window of app1 is created, then preload scripts are downloaded.
2.) While waiting for the preload scripts promise to resolve, create app for "app2" with same uuid is called.  Since app1 is not yet "running" (not set to true until after preloads d/l), app1 is overwritten in corestate by app2 and the mainWindow created in …
=> RUN-5472 - Application creation / run timing issue

src/browser/api_protocol/api_handlers/external_window.ts, src/browser/api_protocol/api_handlers/system.ts
Jira: https://appoji.jira.com/browse/RUN-5463
This change places `System.getAllExternalWindows` and `ExternalWindow.wrap` (sent to core as `register-native-external-window`) behind API security. I've opted to just place these two methods behind security in the interest of simplicity / ease of use:
- These are the two entry points to "doing stuff with native windows". If both are disallowed, it should, to the best of my analysis, be impossible to get info about or do anything to non-OpenFin windows.
- Current changeset uses the same exact flow as other restricted API methods, so we don't need extra explanation or code to make it work. (As opposed to an `ExternalWindow`-level boolean setting, which would require additional code changes and counterintuitively also control …
=> Run 5463 nwi api security

src/browser/api/browser_view.ts, src/browser/api_protocol/api_handlers/browser_view.ts, src/browser/core_state.ts, src/shapes.ts
Enable multiple browser views per window. Allow re-attaching views to different windows
[JS-adapter](https://github.com/HadoukenIO/js-adapter/pull/311)
Notes: Experimentally allow multiple browser views to be attached to one window.
=> Run 5449/run 5192 multi browser view

src/browser/api/system.js, src/browser/api_protocol/api_handlers/system.ts, src/browser/rvm/rvm_message_bus.ts
Added API for user to query the RVM for the versions of all the runtimes installed.
Compatible with RVM 5.3+
fin.system.getInstalledRuntimes( )
Is linked to [this js-adapter PR](https://github.com/HadoukenIO/js-adapter/pull/307)
=> RVM-946 Added GetInstalledRuntimes API

src/browser/api/native_window.ts, src/browser/api/window.js, src/browser/api_protocol/api_handlers/window.ts
Expose Electron's BrowserWindow.center
Added API to center windows
Notes:
=> RUN-5475 - Expose Electron's Window Centering API

src/renderer/api-decorator.js
Sync calls on window load are known to introduce a race condition with MOJO
General testing has been performed while investigating a MOJO timing issue introduced with Electron v5
=> fix(api-decorator): Make 'window/performance-report' ASYNC. 

src/browser/api/window.js
The PR adds a `isUserMovementEnabled` bool field to `window.getInfo()` for users to be able to tell programmatically whether user movement is enabled
Test: https://testing-dashboard.openfin.co/#/app/tests/5d48843a394bc65e455b9a6e/edit
Docs update: https://github.com/HadoukenIO/js-adapter/pull/315
Notes: Added `isUserMovementEnabled` property to `window.getInfo()` that allows to programmatically discover whether user movement is enabled
@rdepena @tgoc99 @pbaize @datamadic
=> RUN-5456 There’s no way of programmatically telling if a window has enabled or disabled user movement

index.js
This PR is to fix the browser process not exiting issue when starting another app with duplicate uuid in different runtime. 
Notes:
=> RUN-5414 browser process not exit when starting an app with duplicate UUID 

index.js
This PR is to fix an infinite message loop issue using duplicate uuid in multi runtime environments. It causes browser process and debug.log size increasing dramatically.
Will add a test later.
Notes:
=> RUN-5484 Fix infinite message loop issue

index.js, src/browser/api_protocol/api_handlers/application.js
This PR fixes two issues:
1) Check if external connection exists when run an app. Otherwise it will cause promise pending. 
2) uuid could be undefined in launchApp when calling launchAndConnect in node adapter. 
Notes:
=> RUN-5503 Should also check external connection with duplicate UUID

src/browser/api/browser_view.ts, src/browser/api/window.js, src/browser/api_protocol/api_handlers/middleware_entity_existence.ts, src/browser/api_protocol/api_handlers/webcontents.ts, src/browser/core_state.ts
The PR adds support for BrowserViews in webcontents API handlers
Notes: Exposed WebContents methods for BrowserViews
@pbaize @rdepena @bschwinn @datamadic 
Tests:
https://testing-dashboard.openfin.co/#/app/tests/5d5597085cca4e5a7198d1df/edit - executeJavaScript
https://testing-dashboard.openfin.co/#/app/tests/5d559ad45cca4e5a7198d1e1/edit - navigate
https://testing-dashboard.openfin.co/#/app/tests/5d559ce05cca4e5a7198d1e3/edit - navigateBack
https://testing-dashboard.openfin.co/#/app/tests/5d559d605cca4e5a7198d1e4/edit - navigateForward
https://testing-dashboard.openfin.co/#/app/tests/5d559d815cca4e5a7198d1e5/edit - stopNavigation
https://testing-dashboard.openfin.co/#/app/tests/5d559dc55cca4e5a7198d1e6/edit - reload
https://testing-dashboard.openfin.co/#/app/tests/5d55a09a5cca4e5a7198d1e8 …
=> RUN-5487 Resolve BrowserView in Webcontents api handler

src/browser/api/webcontents.ts, src/browser/api/window.js
Sets up webcontents event hooks for browserview
Notes: n/a experimental
=> RUN-5206 Set up webcontents eventing

.jshintrc, npm-shrinkwrap.json, package.json
Updates `grunt-contrib-jshint` to `2.1.0` and configures `jshint` to allow for `async/await`
Notes:
=> Update grunt-contrib-jshint to 2.1.0 to allow for async/await

src/browser/api/external_window.ts
Jira: https://appoji.jira.com/projects/RUN/issues/RUN-5508
As of 13.76.44.12, the runtime exposes the idChild property on native window events passed to the core. By only propagating events with `idChild === '0'` (indicating that the event is from the main window), we filter out some eventing from subcomponents that are not currently filtered out by the runtime.
N/A
=> RUN-5508: Reduce noise - only emit main win events

src/browser/disabled_frame_group_tracker.ts
With new logic, happening on every user-generated group move, change to once.  Only bring to front on first move of a user-generated grouped window move.
=> RUN-5518 - Only bring to front on first move of grouped move

Gruntfile.js, npm-shrinkwrap.json
It's necessary as if core is built with older Electron build
doesn't start on MacOS.
Notes:
=> RUN-5579: Updated version of Electron which is used to build core

src/browser/disabled_frame_group_tracker.ts
Reintroducing window transactions to group moves. This leverages the ability that we now have in the core to get raw window positions with the shadows factored out for win10 framed windows. 
The `any` casting will be removed once we introduce the proper types on the runtime side.
n/a internal
Notes:
=> RUN-5309 Task/reintroduce transactions

index.js, src/browser/api/application.js, src/browser/api/file_download.ts, src/browser/api/window.js, src/browser/api_protocol/api_handlers/api_policy_processor.ts, src/browser/api_protocol/api_handlers/application.js, src/browser/api_protocol/api_handlers/authorization.js, src/browser/api_protocol/api_handlers/deprecated_external_windowing_middleware.ts, src/browser/convert_options.js, src/browser/core_state.ts, src/browser/navigation_validation.ts, src/browser/web_request_handler.ts, src/modules.d.ts, src/renderer/api-decorator.js
Switch to using webcontents id rather than browserwindow id for core ids.
Notes: n/a pre-req for browser-view support
=> RUN-5507 Switch to using webcontents id rather than browserwindow id

src/browser/api/application.js, src/browser/api/browser_view.ts, src/browser/api/window.js, src/browser/api_protocol/api_handlers/application.js, src/browser/api_protocol/api_handlers/browser_view.ts, src/browser/api_protocol/api_handlers/window.ts, src/browser/core_state.ts
Add methods to query browserview state
Notes: n/a experimental browserview
=> RUN-5469 BrowserView state methods

src/browser/disabled_frame_group_tracker.ts
Channel onDisconnection from the provider (on client disconnection) was not working multi-runtime. This PR makes it work.  The services team needs this for notifications.
Goes with [this js-adapter PR](https://github.com/HadoukenIO/js-adapter/pull/339)
Notes: Fixed bug where channel onDisconnection from the provider was not working across runtimes.
=> Run-5584 Multi runtime channel disconnect

src/browser/web_request_handler.ts
New network service web request api implementation always reassigns
headers to whatever is passed in callback. Omitting headers when we did
not modify them ended up removing all previously assigned headers from
request.
=> RUN-5537: Always pass headers in onBeforeSendHeaders callback.

Gruntfile.js, npm-shrinkwrap.json
Bump the versions for electron-rebuild and electron. Also, don't rebuild `optionalDependencies` in package.json on Windows. This is because `unix-dgram` is only needed on non-Windows systems and it gives us a meaningless error on Windows.
Notes:  N/A - Internal
=> RUN-5606 chore: Bump electron-rebuild

src/browser/convert_options.js
Remove the legacy configuration for sandboxed node in renderers
https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5d7fee2d7bacba7f712054b5
N/A - Internal Only
=> RUN-5516: task: Remove legacy configuration

src/browser/core_state.ts, src/shapes.ts
Adds EntityType and EntityInfo for BrowserView
New test https://testing-dashboard.openfin.co/#/app/tests/5d8247927ba87401eaf564ee/edit
Notes:
=> Browser view entity type

src/browser/api/browser_view.ts, src/browser/convert_options.js
Uses affinity to group same origin render processes
Notes:
=> RUN-5602 Use affinity for render process management of BrowserViews

src/browser/api/browser_view.ts
Await loadUrl in browserview creation. This means getInfo timing issues go away. It also means browserview creation can fail on a bad url.
new tests: https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5d8138947ba87401eaf564be
Notes: n/a experimental
=> RUN-5604 Await loadUrl in browserview creation

src/renderer/api-decorator.js
Handles the case where creating a window inside a browserview through either `window.open()` or `fin.Window.create()` causes the renderer to hang
Test: https://testing-dashboard.openfin.co/#/app/tests/5d8509a97ba87401eaf5658d/edit
Notes: Fixes renderer hang when creating a window inside BrowserView
@pbaize @rdepena @MichaelMCoates
=> RUN-5492 Throw error on window.open/fin.Window.create inside BrowserView

src/browser/api/webcontents.ts, src/browser/api/window.js, src/browser/rvm/utils.ts
Adds RVM logging for console messages inside browserviews in the same way we do for windows.
**NOTE**
For this to work we need to wait for (@MichaelMCoates)'s changes that will apply `hookWebContentsEvents(...)` to webcontents created by browserviews. Until then everything will build fine but the actual logging won't happen.
@rdepena @pbaize @datamadic 
Notes: Added RVM logging inside BrowserViews
=> RUN-5577  Logging for browserview

src/renderer/node-less.js
Execute  preload scripts after API modules have been evaluated
Relies on https://github.com/openfin/runtime/pull/1636
N/A - Internal Only
=> RUN-5534 fix: Execute preload scripts after API modules

src/browser/of_events.ts
Sets up event propagation from BrowserView up to Application and System.
Tests:
https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5d88dfaf7ba87401eaf565df
Notes: 
- BrowserView events now propagate up to Application and System.
=> [RUN-5625] Propagate events from BrowserView to Application and System

src/browser/api/browser_view.ts
Rearranges the BrowserView events during creation so they emit in the following order:
1. Created
2. Attached
3. Shown
Notes:
=> Rearrage BrowserView Eventing During Creation

src/browser/api/browser_view.ts
Fixes a bug that prevents a BrowserView from attaching back to the window it was originally attached to. 
Bug Repro:
1. Create a BrowserView on Window A.
2. Attach the BV to Window B.
3. Attempt to attach the BV back to Window A.
Expected: BV Shows up on Window A.
Actual: BV stays on Window B.
To fix, we simply call removeBrowserView with the old window.
Notes:
=> Bugfix - Call removeBrowserView on oldWin so that we can attach BrowserViews back and forth
