src/browser/api_protocol/api_handlers/window.js
src/renderer/api-decorator.js

https://github.com/openfin/runtime/pull/401

RUN-2980: Iframe reload clears subscriptions for main frame [6.49.19.*]

---

src/browser/convert_options.js

[develop] backgroundThrottling should be false by default

---

src/browser/api/interappbus.js
src/browser/api_protocol/api_handlers/interappbus.js
src/browser/api_protocol/api_handlers/mesh_middleware.ts
src/browser/of_events.ts

[Test](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5924e4af5114ac10ca6db456) was clean — except for _Notification.close (from onShow)_ failing + two fails which passed on retest.

RUN-3017 normalize subscriber event constants

---

src/browser/animations.js
src/browser/api/window.js
src/browser/bounds_changed_state_cache.js
src/browser/bounds_changed_state_tracker.js
src/browser/clip_bounds.ts
src/browser/deferred.ts
src/common/safe_int.ts
test/safe_int.tests.ts

[Test](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5925d2585114ac10ca6db46f) was clean:
* _Notification.close (from onShow)_ failed
* one other test failed by passed on manual retest
Note: Change to Gruntfile.js here is exactly the same as that in #22, because I didn't want my new object literals to be beautified (expanded to multiple lines).

RUN-3007: More fractional bounds

---

src/browser/api/window.js

No API changes, internal implementation of RMB menu logic only.
Manual tests shows menu behavior unchanged for standard OpenFin windows, and fixed for EmbeddedView windows.
Test Results (took multiple runs):
https://testing-dashboard.openfin.co/#/app/sessions/api/completed/592dd91d998bc04e20cc6c90
https://testing-dashboard.openfin.co/#/app/sessions/api/completed/592dd940998bc04e20cc6c92

RUN-3015 Fixed context menu does not display when windows are Embedded.

---

src/browser/convert_options.js

Sister PR: https://github.com/openfin/javascript-adapter/pull/311

RUN-2966 expose webSecurity

---

index.js
src/browser/api/application.js
src/browser/rvm/rvm_message_bus.ts

[test well](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/593ee6536ea8aa729bafe024) All fails are at parody with a vanilla build
This front runs a hotfix

Do not double stringify eventing payloads

---

index.js
src/browser/api/system.js
src/browser/api_protocol/api_handlers/system.js
src/browser/rvm/rvm_message_bus.ts

@StevenEBarbaro @HarsimranSingh @datamadic @whyn07m3 check it out.
[Test resuts](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/593f017e34e44123d883e941)
[Vanilla 5.49.21.12 results](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/593f044134e44123d883e942)

RUN-2945 Worked with RVM to fix a few shape issues, added downloadRuntime API call

---

index.js
src/browser/api/window.js

https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5942a0cf0f8f4a3476957121

(HOTFIX from .18) RUN-3058: unhook global accelerators on window close

---

src/browser/rvm/runtime_initiated_topics/app_assets.ts

@StevenEBarbaro @HarsimranSingh @whyn07m3 @datamadic check it out
[test results](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5942dc780f8f4a3476957128)

RUN-3053 Fixed issue where asset resolution was not working

---

src/browser/rvm/runtime_initiated_topics/app_assets.ts

@StevenEBarbaro @HarsimranSingh @datamadic @whyn07m3 Check it out

RUN-3053 Fixed issue where asset resolution was not working, now on 7

---

src/renderer/api-decorator.js

Do not subscribe directly to the unload event.
[tests well](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59511ca50c10170217365895)
[added test](https://testing-dashboard.openfin.co/#/app/tests/595113230c10170217365894/edit)

RUN-2994 close hanging window 6.49.21/staging

---

src/renderer/api-decorator.js

Do not subscribe directly to the unload event.
[tests well](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5951638f0c101702173658a8) fails pass in isolation
[added test](https://testing-dashboard.openfin.co/#/app/tests/595113230c10170217365894/edit)

RUN-2994 close hanging window

---

src/browser/api/system.js
src/browser/core_state.ts

[PR To V6 Staging](https://github.com/HadoukenIO/core/pull/79)
Test results: pending.
@wenjunche @StevenEBarbaro @HarsimranSingh @whyn07m3 @datamadic @joneit please review.

RUN-3067 downloadRuntime fix

---

Gruntfile.js
index.js
src/browser/connection_manager.ts
src/browser/port_discovery.ts

@joneit @datamadic @HarsimranSingh @StevenEBarbaro @wenjunche 
#89 applied to v6 staging.
[Test results](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/596e88e7a3c7663182518f9d)

RUN-3034 Realms do not fully isolate under multi runtime

---

src/browser/api_protocol/api_handlers/application.js

@wenjunche @StevenEBarbaro @HarsimranSingh @whyn07m3 @VanessaSergeon @datamadic @joneit 
Fixed issue introduced in [compare link](https://github.com/HadoukenIO/core/commit/362c84c5c2aaeae8038fc4f07e1be1d9b185c4f4#diff-dd883de5703030a371af2cdd9ad72616R409).
[Test results](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/596e6e26a3c7663182518f95)
[Failure re-run](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/596e6e72a3c7663182518f96)

RUN-3086 Docking of external windows not working

---

package.json

fixed runtime-p2p to use ssh

---

src/browser/api/application.js
src/browser/api/window.js

This PR is pending approval of #91 (v7 version).

RUN-3145 Emit diagnostic events from Window

---

src/browser/api/window.js

RUN-3055 don't set opacity unless less than 1

---

src/browser/api/window.js

@StevenEBarbaro @HarsimranSingh @datamadic fixed.

RUN-3177 fixed errors on closing because of event timing.

---

src/browser/subscription_manager.js

@rdepena @StevenEBarbaro @HarsimranSingh 
this is the hotfix to the hotfix...

unload hotfix

---

src/browser/preload_scripts.ts

Regression [**tests**](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/598dd98bd2a02971da3a62be) passed (no relevant fails).
I simulated a fetch failure on my local to demonstrate the problem which resolved after fix applied.

RUN-3234 Preload fetch may fulfill early

---

src/browser/api/system.js
src/browser/api/window.js
src/browser/api_protocol/api_handlers/system.js
src/renderer/api-decorator.js

Regression [**tests**](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/598df4cfd2a02971da3a62c2) passed (no relevant fails).

RUN-3236 Short circuit preload API calls when no preloads

---

src/browser/api/system.js
src/browser/api_protocol/api_handlers/system.js

added method to allow users to get existing app asset info

RUN-3260: added method to get app asset info

---

index.js
src/browser/api/application.js

Cleanup as per @HarsimranSingh 
Tests:
- [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59a59071d2a02971da3a6378)
- [Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59a58ff5d2a02971da3a6377)

RUN-2760 Fix code review comments

---

src/renderer/api-decorator.js

This PR is part of fix for RUN-3127. See comment in code.

RUN-3127 Fix problem with "backgroundColor" window option.

---

src/browser/api_protocol/api_handlers/authorization.js
src/browser/api_protocol/api_handlers/middleware_entity_existence.ts

@HarsimranSingh @StevenEBarbaro @datamadic Missing code in Develop. I must have forgotten.

7.53.23/staging

---

src/renderer/api-decorator.js

Prevent iframes from making windowing api calls on startup
[tests well](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59b1902cd2a02971da3a63d4)
[added test](https://testing-dashboard.openfin.co/#/app/tests/59b1a9a7d2a02971da3a63d5/edit)

RUN-3128 bugfix iframe restore breaking maximize 

---

src/browser/api/application.js
src/browser/api_protocol/api_handlers/authorization.js

when creating application or external-application, need to check if specified uuid exists in both places.

RUN-3305 check uuid in both applications and external-applications

---

index.js

Show error popup only if manifest URL is different from the existing Running instance.

RUN-3279 check duplicate uuid if manifestUrl is different

---

src/browser/api/window.js
src/browser/api_protocol/api_handlers/application.js
src/browser/session.ts
src/common/microsoft.ts

Also collapsed some whitespace.
[Tests](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59c16f307cb79f732d10c36a)

RUN-3335 Normalize Microsoft constants

---

src/browser/clip_bounds.ts
src/browser/deferred.ts
src/modules.d.ts
src/shapes.ts

**[Tests](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59c96c277cb79f732d10c3ac).**
This is a casual general improvement PR and can slip to next sprint considering this sprint has so much to merge already.

RUN-3365 Improve BrowserWindow interface definition

---

src/browser/convert_options.js
src/renderer/api-decorator.js

[Tested](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59ce79c87cb79f732d10c3fc) clean.
Tests include the following new test:
* [`new Window (preload) (default inheritance opt out)`](https://testing-dashboard.openfin.co/#/app/tests/59ce76327cb79f732d10c3fb/edit)
Note however that this test is currently set to private (until merge).

RUN-3265 Let falsy preload option prevent inheritance

---

src/browser/convert_options.js

check if startup_app is available first.

RUN-3377 fixed bug that caused error in getStartupAppOptions

---

index.js
package.json
src/browser/connection_manager.ts
src/browser/port_discovery.ts

A description of these changes can be found:
https://github.com/openfin/Internal-Wiki/issues/15
[Win7 Tests](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59d4f75d7cb79f732d10c438)
[Win10 Tests](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59d4f7cb7cb79f732d10c43a)

RUN-3329 Multi runtime defaults to on now.

---

src/browser/convert_options.js

Sister PR to https://github.com/openfin/runtime/pull/580 (already merged)

RUN-2974 default backgroundColor to #0FFF when transparent is true

---

README.md

Slack badge

---

src/browser/api/window.js
src/renderer/api-decorator.js

Test results
[W10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59e8068aaf26a25be2ffc903)
[W7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59e8060faf26a25be2ffc902)

RUN-3460: iframes not getting preload scripts

---

src/browser/api/application.js

[W10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59ea1675af26a25be2ffc90a)
[W7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59ea15c7af26a25be2ffc909)

RUN-3464: Fixed runWithRVM

---

index.js
src/browser/core_state.ts

Test results:
[W7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59ee2222af26a25be2ffc912)
[W10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59ee2267af26a25be2ffc913)
[Runtime PR](https://github.com/openfin/runtime/pull/669)

RUN-3471: client cert select dialog not working

---

src/browser/api/system.js
src/browser/api_protocol/api_handlers/system.js

[Adapter PR](https://github.com/openfin/javascript-adapter/pull/350)
[Win 10 test results (failed passed in isolation)](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59fa2bbdaf26a25be2ffc9dc)
[New Test REG_BINARY](https://testing-dashboard.openfin.co/#/app/tests/59ef9a8daf26a25be2ffc948/edit)
[New Test REG_DWORD](https://testing-dashboard.openfin.co/#/app/tests/59ef9909af26a25be2ffc945/edit)
[New Test REG_EXPAND_SZ](https://testing-dashboard.openfin.co/#/app/tests/59ef9b2baf26a25be2ffc949/edit)
[New Test REG_MULTI_SZ](https://testing-dashboard.openfin.co/#/app/tests/59ef9991af26a25be2ffc947/edit)
[New Test REG_SZ](https://testing-dashboard.openfin.co/#/app/tests/59ef990caf26a25be2ffc946/edit)

RUN-3503 add system.readRegistryValue

---

src/renderer/api-decorator.js

⚠️   **.25 regression fix**
ℹ️ Fixes preload scripts not properly setting up their final states
• [Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59fb4a3aaf26a25be2ffc9fd)
• [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59fb4a7baf26a25be2ffc9fe)

RUN-3528 regression: preload scripts & final states

---

src/browser/api/system.js
src/browser/api_protocol/api_handlers/system.js

[Adapter](https://github.com/openfin/javascript-adapter/pull/351)
Test results:
[W10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59f38682af26a25be2ffc988)
[W7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59f3862faf26a25be2ffc987)
[New Test](https://testing-dashboard.openfin.co/#/app/tests/59f38c08af26a25be2ffc989/edit)

RUN-3510: added system.getCookies

---

src/browser/cached_resource_fetcher.ts
src/browser/preload_scripts.ts

ℹ️ Improves NET module to handle bad URLs when fetching resources
➕ New test: [window.getInfo (preloadState) (load-failed)](https://testing-dashboard.openfin.co/#/app/tests/59ef83c0af26a25be2ffc931/edit)
• [Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59fcc935af26a25be2ffca3b)
• [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59fcc9b3af26a25be2ffca3c)

RUN-3472 fixes NET module to handle bad URLs and fixes fetching events

---

src/browser/api/application.js
src/browser/api/system.js
src/browser/api/window.js
src/browser/convert_options.js
src/browser/preload_scripts.ts
src/renderer/api-decorator.js
src/shapes.ts

ℹ️ This PR changes shapes for preload scripts and plugins
👫 Coupled with this [javascript-adapter PR](https://github.com/openfin/javascript-adapter/pull/354)
Tests: updated tests to use new shapes, keeping them private, running through them locally myself, will publish after merging this and having a build
✅ Test results (Test #406 needs updating):
• [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/59fcdf44af26a25be2ffca44)

RUN-3469 changed preload scripts and plugin modules shapes

---

src/browser/api/notifications/observable_sequences.ts
src/browser/api/notifications/shapes.ts
src/browser/api/notifications/subscriptions.ts

Add opacity option to notifications.
[Related JS-Adapter PR](https://github.com/openfin/javascript-adapter/pull/352)

RUN-3481 add opacity to notifications

---

src/browser/api_protocol/api_handlers/api_policy_processor.ts
src/browser/api_protocol/api_handlers/system.js
src/browser/api_protocol/shapes.ts

Test results:
[W10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a007ad8af26a25be2ffca52)
[W7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a007ad8af26a25be2ffca52)

RUN-3505: Update spec for registry security policy

---

src/browser/cached_resource_fetcher.ts

@rdepena @StevenEBarbaro @rdepena @HarsimranSingh @tgoc99 @whyn07m3 
Lets get this through fast-ish... please review

Hotfix check the Cache dir exists

---

src/browser/cached_resource_fetcher.ts

[hotfix] check the cache dir exists (#235)

Merge 8.56.26/staging into develop

---

src/renderer/api-decorator.js

[Win 7 Test Results](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a0358b81573627ee43842a6) ✅ 
[Win 10 Test Results](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a03591c1573627ee43842a7) ✅

RUN-3553 fix ctrl + scroll for zooming [hotfix]

---

src/browser/cached_resource_fetcher.ts

@datamadic @StevenEBarbaro @wenjunche @whyn07m3 check it out.

RUN-3596 if not subscribed to request errors, the net module will throw an exception.

---

src/browser/cached_resource_fetcher.ts

Tests
[W10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a105e729a4b9e06a9723a46)
[W10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a105e109a4b9e06a9723a45)

RUN-3618: Feature/cached fetch enoent 8.56.26

---

src/browser/api_protocol/api_handlers/api_policy_processor.ts
src/browser/rvm/rvm_message_bus.ts
src/modules.d.ts

[W10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a0236271573627ee4384296)
[W7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a0235a81573627ee4384295)

RUN-3005: support new format of API policy definitions

---

src/browser/api/application.js
src/browser/api/system.js
src/browser/api_protocol/api_handlers/application.js
src/browser/api_protocol/api_handlers/system.js
src/browser/preload_scripts.ts

[JS adapter PR](https://github.com/openfin/javascript-adapter/pull/359)
Tests:
[W10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a0475041573627ee43842bd)
[W7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a0474c01573627ee43842bc)

RUN-3536: preload script reload

---

src/browser/api/window.js
src/browser/api_protocol/transport_strategy/elipc_strategy.ts
src/browser/core_state.ts
src/shapes.ts

Tests
[W10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a1068a59a4b9e06a9723a4b)
[W7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a1068389a4b9e06a9723a49)

RUN-3578: Feature/iframe dup iab messages

---

src/browser/api/application.js
src/browser/api/system.js
src/browser/cached_resource_fetcher.ts
src/browser/convert_options.js
src/modules.d.ts

Tests
[W10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a21d24ee01cd83250859178)
[W7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a21f064e01cd8325085917b)

RUN-3663: Feature/replace resource fetcher

---

Gruntfile.js
package.json
src/renderer/main.js

Related to this https://github.com/HadoukenIO/js-adapter/pull/68

js-adapter is no longer packaged as an asar

---

src/browser/api/application.js

:white_check_mark: Test Results, including new test for the scenario:
[Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a393b856f202a5432b79f6c)
[Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a3939646f202a5432b79f6b)

RUN-3593 return only true or false for Application.isRunning() method

---

src/browser/preload_scripts.ts

Test results: 
[Win7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a3ac5156f202a5432b79f7c)
[Win10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a3ac5986f202a5432b79f7f)

RUN-3721 Fixed issue where we expected an array for preload processing.

---

src/renderer/api-decorator.js
src/renderer/main.js

@StevenEBarbaro @rdepena @HarsimranSingh 
[tests well](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a544e4cbd581266877d665c)

RUN-3252 attempt to launch the crash reporter on the render side

---

src/browser/api/window.js

https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a451b626f202a5432b79f95

RUN-3731 - Async context menu

---

src/browser/api/application.js
src/browser/api/system.js
src/browser/api/window.js
src/browser/cached_resource_fetcher.ts
src/browser/convert_options.js
src/common/main.ts

This PR includes the fix for `file://` URLs and adds some improvements with helper functions
Will post test results (they will be good) in a few hours, and then will also write a test. This is PR is open now so that anyone who cares can start reviewing.
**Test:** [automatic or manual (coming soon...)]()
**Test results:** [Windows 7 (coming soon...)](), [Windows 10 (coming soon...)]()

RUN-3755 fixed file URL problems

---

src/browser/api/window.js
src/browser/convert_options.js
src/shapes.ts

Tests:
[W10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a2963d56f202a5432b79ef7)
[W7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a29634a6f202a5432b79ef6)
[javascript adapter PR](https://github.com/openfin/javascript-adapter/pull/366) 
[Runtime PR](https://github.com/openfin/runtime/pull/764)

RUN-3656: support for resizeSides

---

src/browser/preload_scripts.ts

[W10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a5ba7dfbd581266877d66b7)
[W7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a5ba72fbd581266877d66b6)

RUN-3758 preload scripts should load for iframes

---

src/browser/transports/wm_copydata.ts

corresponding PR for runtime change [#798](https://github.com/openfin/runtime/pull/798)

RUN-3600 implemented message time and retry feature

---

src/browser/api/application.js
src/browser/api/system.js
src/browser/api_protocol/api_handlers/system.js
src/browser/authentication_delegate.js
src/browser/cached_resource_fetcher.ts
src/login/index.html

[W7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a4d5662bd581266877d663a)
[W10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a4d56ebbd581266877d663b)
[Javascript PR](https://github.com/openfin/javascript-adapter/pull/373)

RUN-3739 auth resource fetch

---

src/browser/api_protocol/transport_strategy/elipc_strategy.ts
src/browser/web_request_handler.ts
src/renderer/api-decorator.js

This adds the null checks to avoid the runtime exception when center clicking. It does not resolve the issue of center clicking opening a blank window.

RUN-3386 null checks to avoid exception

---

src/browser/cached_resource_fetcher.ts

RUN-3785: Fixed a bug with reading local file in fetchReadFile

---

index.js

Win10 and Mac_OS dash board test works well.

RUN-3769: enable copy paste accelerator globally

---

Gruntfile.js
npm-shrinkwrap.json
package.json
src/browser/api/notifications/note_action.ts
src/browser/api/notifications/observable_sequences.ts
src/browser/api/notifications/shapes.ts
src/browser/api/notifications/subscriptions.ts
src/modules.d.ts

This PR is fixing some tslint issues.
Test results: [Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a7322633f32861e82b77cfb)  [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a73233b3f32861e82b77cfd)

RUN-3797 Fix some tslint issues

---

src/browser/api/window.js

Tests
[W10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a78a27483591b524677a72c)
[W7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a78a1d383591b524677a72b)
[Runtime PR](https://github.com/openfin/runtime/pull/823)
[adapter](https://github.com/openfin/javascript-adapter/pull/390)
[new test](https://testing-dashboard.openfin.co/#/app/tests/5a7b52d383591b524677a752/edit)
[Runtime Doc](https://github.com/openfin/runtime/pull/826)

RUN-3809 Add closing as reason for hidden event

---

src/browser/api/window.js

[W10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a7b49db83591b524677a751)
[W7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a7b495183591b524677a750)
[Adapter](https://github.com/openfin/javascript-adapter/pull/391)
[new test](https://testing-dashboard.openfin.co/#/app/tests/5a7b5c7183591b524677a753/edit)

RUN-3815: customData updatable

---

src/browser/api/application.js
src/browser/api/window.js
src/browser/rvm/rvm_message_bus.ts

[runtime](https://github.com/openfin/runtime/pull/828)
[javascript-adapter](https://github.com/openfin/javascript-adapter/pull/392)
New Tests:
https://testing-dashboard.openfin.co/#/app/tests/5a7228e03f32861e82b77cf4/edit
https://testing-dashboard.openfin.co/#/app/tests/5a7225283f32861e82b77cf3/edit
https://testing-dashboard.openfin.co/#/app/tests/5a72131a3f32861e82b77cf0/edit
https://testing-dashboard.openfin.co/#/app/tests/5a7213163f32861e82b77cef/edit

 RUN-3777 add reason to crashed event

---

src/browser/api_protocol/api_handlers/window.js

Test results:
[W10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a81ec6f6a994a57faa5c899)
[W7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a81eb686a994a57faa5c898)
Details in [Jira](https://appoji.jira.com/browse/RUN-3823)

RUN-3823 exception from Window.getGroup

---

src/browser/cached_resource_fetcher.ts

RUN-3785: Fixed a bug with reading local file in fetchReadFile (#298)
Looks good. [tests here](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a6a47cb3f32861e82b77c8b)

Merge 8.56.28/staging into develop

---

index.js

[runtime pr](https://github.com/openfin/runtime/pull/832)

RUN-3800 log out gp and build arch

---

src/browser/remote_subscriptions.ts

**About**
This PR fixes a regression in .28 for failing remote subscriptions in multi-runtime
**New automated test**
[Application.createFromManifest (two multi-runtime apps)](https://testing-dashboard.openfin.co/#/app/tests/5a86fade6a994a57faa5c908/edit)
**Test results**
✅ [Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a8717666a994a57faa5c919)
✅ [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a87184e6a994a57faa5c91a)

RUN-3830 fixed .createFromManifest regression

---

Gruntfile.js
LICENSE
README.md
src/browser/api/external_application.ts
src/browser/api_protocol/api_handlers/api_policy_processor.ts
src/browser/api_protocol/api_handlers/authorization.js
src/browser/api_protocol/api_handlers/external_application.ts
src/browser/api_protocol/api_handlers/mesh_middleware.ts
src/browser/api_protocol/transport_strategy/base_handler.ts
src/browser/api_protocol/transport_strategy/ws_strategy.ts
src/browser/connection_manager.ts
src/browser/external_window_event_adapter.js
src/browser/plugins.ts
src/browser/port_discovery.ts
src/browser/remote_subscriptions.ts
src/browser/rvm/runtime_initiated_topics/app_assets.ts
src/browser/rvm/runtime_initiated_topics/rvm_info.js
src/browser/rvm/rvm_message_bus.ts
src/browser/rvm/utils.ts
src/browser/transport.ts
src/browser/transports/base.ts
src/browser/transports/chromium_ipc.ts
src/browser/transports/chromium_socket.ts
src/browser/transports/electron_ipc.ts
src/browser/transports/socket_server.js
src/browser/transports/wm_copydata.ts
src/common/safe_int.ts

Removed commercial license from files and project.

---

src/renderer/node-less.js

[W10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a8f1cd86a994a57faa5c965)
[W7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a8f1c046a994a57faa5c964)
[Runtime](https://github.com/openfin/runtime/pull/850)

RUN-3845 Fixed Window.executeJavascript in node-less renderer

---

src/browser/api/system.js
src/browser/api_protocol/api_handlers/system.js

[W10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a9570ab6a994a57faa5c984)
[W7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5a956fd36a994a57faa5c983)
[New Test](https://testing-dashboard.openfin.co/#/app/tests/5a956ecb6a994a57faa5c982/edit)
[Adapter](https://github.com/openfin/javascript-adapter/pull/399)

RUN-3874 flush cookies

---

src/browser/api/service.ts

Remove superfluous nesting of registerService ack

RUN-3812 - fix shape of registerService ack

---

src/browser/convert_options.js

[W10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5aa088126a994a57faa5ca35)
[W7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5aa086ec6a994a57faa5ca34)
[Runtime](https://github.com/openfin/runtime/pull/870)

RUN-3905: API injection for cross origin node-less iframes

---

Gruntfile.js
npm-shrinkwrap.json
package.json
src/browser/connection_manager.ts
src/browser/runtime_p2p/emitter_map.ts
src/browser/runtime_p2p/peer_connection_manager.ts
test/emitter_map.tests.ts
test/peer_connection_manager.tests.ts

Porting the [runtime-p2p](https://github.com/openfin/runtime-p2p) repository into the core.
Test results: 
[Win 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5aa7e4876a994a57faa5ca66)
[Win 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5aa7e5186a994a57faa5ca67)

RUN-3895 Moved runtime-p2p into the core project.

---

npm-shrinkwrap.json
package.json

RUN-3895 remove optional dependencies from npm-shrinkwrap to fix build (#357)

Merge staging into develop

---

src/browser/api/system.js
src/browser/api_protocol/api_handlers/system.js

Tests
[W10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5ab3bf196a994a57faa5caf6)
[W7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5ab3be906a994a57faa5caf5)
[API PR](https://github.com/openfin/javascript-adapter/pull/410)
API output: 
{"manifestUrl":"http://localhost:8081/app.json","port":9696,"securityRealm":"test","version":"8.56.30.28"}

RUN-3943: added System.getRuntimeInfo

---

npm-shrinkwrap.json
package.json

Version bump of the js-adapter.
[Win7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5ac441414ecc2a37d5a483e0)
[Win10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5ac442104ecc2a37d5a483e2)

Upgraded to new version of the js-adapter

---

src/browser/api_protocol/api_handlers/clipboard.ts
src/modules.d.ts

This PR is fixing electron breaking api for clipboard.
Tests: [Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5ac520244ecc2a37d5a483ed)   [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5ac51d244ecc2a37d5a483ec)

RUN-3964 fix insufficient number of arguments error

---

src/renderer/node-less.js

Related to https://github.com/openfin/runtime/pull/911

RUN-4005 - remove warnings for nodeless renderers

---

src/browser/api/system.js
src/browser/api/window.js
src/browser/api_protocol/api_handlers/system.js
src/browser/api_protocol/api_handlers/window.js
src/browser/convert_options.js
src/browser/plugins.ts
src/renderer/api-decorator.js
src/renderer/main.js
src/shapes.ts

ℹ️ This PR removes old logic for synchronous plugin loading implementation.
⛓ [Chained with this PR](https://github.com/openfin/javascript-adapter/pull/414)
✅ [Test results Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5ace41fe4ecc2a37d5a4844e)
✅ [Test results Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5ace43694ecc2a37d5a4844f)
➕ Automated tests that cover async plugin implementation:
1. [Plugins: one plugin](https://testing-dashboard.openfin.co/#/app/tests/59ef9292af26a25be2ffc942/edit)
1. [Plugins: two plugins](https://testing-dashboard.openfin.co/#/app/tests/59efa625af26a25be2ffc94c/edit)
1. [Plugins: notification](https://testing-dashboard.openfin.co/#/app/tests/59fb2517af26a25be2ffc9e9/edit)
1. [Plugins: …

RUN-3907 removed old sync plugin loading logic

---

src/browser/api/window.js
src/browser/api_protocol/api_handlers/middleware_entity_existence.ts
src/browser/api_protocol/api_handlers/window.js
src/browser/core_state.ts
src/renderer/api-decorator.js

[Sister PR](https://github.com/openfin/javascript-adapter/pull/423)

RUN-4045 register window name early in creation

---

src/browser/api_protocol/api_handlers/interappbus.js

✅ Test Result (with added test case)
[Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5ae9ec4a4ecc2a37d5a485c0)
[Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5ae9eca64ecc2a37d5a485c1)

RUN-4067 fixed IAB bug of missing subscription

---

src/browser/api/system.js
src/browser/api_protocol/api_handlers/system.js
src/browser/plugins.ts
src/shapes.ts

ℹ️ PR's changes include:
1. `fin.desktop.Plugin.import` accepts a string instead of an object
2. Supports lookup of plugin name in `services` key of a manifest
Chained with these PRs:
⛓ [javascript-adapter PR](https://github.com/openfin/javascript-adapter/pull/425)
⛓ [js-adapter PR](https://github.com/HadoukenIO/js-adapter/pull/118)
✅ [Automated test results: Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5ae38a5a4ecc2a37d5a48568)
✅ [Automated test results: Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5ae38bc64ecc2a37d5a4856b)
**Modified automated tests for Plugins:**
1. [Plugins: one plugin](https://testing-dashboard.openfin.co/#/app/tests/59ef9292af26a25be2ffc942/edit)
1. [Plugins: two …

RUN-4033 Plugin.import(string)

---

src/browser/convert_options.js

Tests: 
[Win 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5af9f5a24ecc2a37d5a48661)
[Win 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5af9f42f4ecc2a37d5a4865e)

API V2 on by default.

---

src/renderer/api-decorator.js

Specifically by [This PR](https://github.com/openfin/javascript-adapter/pull/427/files)
Tests
[Win 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5afb210a4ecc2a37d5a4867b)
[Win 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5afb227b4ecc2a37d5a4867f)

Added isMainframe to our internals structure so it can be consumed by the adapters.

---

index.js

✅ Test Results:
[Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5afe689d4ecc2a37d5a486d3)
[Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5afe69b24ecc2a37d5a486d4)

RUN-4136 fixed bug that port number was not sent in port discovery

---

index.js
src/browser/api/window.js

Rewrite user_data & cache directory for MAC

RUN-3981: override user_data & cache directory for MAC

---

src/browser/convert_options.js

[Runtime](https://github.com/openfin/runtime/pull/1018)
Tests
[W7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b01eec64ecc2a37d5a486f6)
[W10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b01efec4ecc2a37d5a486f7)

RUN-4144: Chromium Spellcheck Support V9

---

src/browser/api/interappbus.js

**New automated test:**
➕ [InterApplicationBus.subscribe (listener's "name" in iframe)](https://testing-dashboard.openfin.co/#/app/tests/5b158741f2f2e22fa4b7c26b/edit)
**Test results:**
✅ [Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b16de73f2f2e22fa4b7c275)
✅ [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b16df72f2f2e22fa4b7c276)
✅ JS adapter tests: no new errors
✅ Java adapter tests: no new errors

RUN-4095 fixed source identity for IAB publish

---

npm-shrinkwrap.json
package.json

test results:
[win7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b1ac0bcf2f2e22fa4b7c2cc)
[win10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b1ac1c1f2f2e22fa4b7c2cd)

Bump version of the js-adapter.

---

src/browser/api/application.js
src/browser/api/window.js
src/browser/cached_resource_fetcher.ts
src/browser/clip_bounds.ts
src/browser/core_state.ts
src/browser/deferred.ts
src/browser/preload_scripts.ts
src/common/main.ts
src/modules.d.ts
src/shapes.ts

⚠️ This is a v8 fix
**About**
These changes make resource fetcher use session cookies when its making requests
✅ [Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b1fdfe254b21953031f35b4)
✅ [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b1fe02a54b21953031f35b5)

RUN-4084 net module should use cookies

---

index.js
src/browser/port_discovery.ts
src/browser/transport.ts
src/browser/transports/base.ts
src/browser/transports/chromium_ipc.ts
src/browser/transports/wm_copydata.ts
src/modules.d.ts

Doing a little cleanup before adding in a new transport for unix domain sockets.
Tests:
[Win 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b117228f2f2e22fa4b7c262)
[Win 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b117367f2f2e22fa4b7c263)

RUN-4183 refactor port discovery and transports

---

npm-shrinkwrap.json
package.json

Tests:
[Win7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b2165ee54b21953031f35c9)
[Win10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b21672054b21953031f35ca)
[Diff between versions](https://github.com/HadoukenIO/js-adapter/compare/53945c9e0f34810bccefdf2240ff88781357dda7...develop)

Using alpha.5 version of the js-adapter

---

src/browser/api/application.js
src/browser/api_protocol/api_handlers/application.js
src/browser/core_state.ts

Add manifest, manifestUrl, and parentUuid to getInfo call.  
[Win7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b21519454b21953031f35c6)
[Win10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b21519454b21953031f35c7)
New Tests:
[getinfo t3](https://testing-dashboard.openfin.co/#/app/tests/5b118f15f2f2e22fa4b7c266/edit)
[multi-runtime getinfo t4](https://testing-dashboard.openfin.co/#/app/tests/5b155938f2f2e22fa4b7c269/edit)
[docs in javascript-adapter](https://github.com/openfin/javascript-adapter/pull/439)

RUN-4032 Add manifest to get info

---

Gruntfile.js
npm-shrinkwrap.json
package.json

ℹ️ **About**
This PR updates TypeScript to the latest stable version 2.9.2
✅ [Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b3e7bd554b21953031f368b)
✅ [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b3e7d2054b21953031f368c)

RUN-4239 updated TypeScript

---

src/browser/api/notifications/subscriptions.ts
src/browser/monitor_info.js

ℹ️ **About**
This PR fixes uncaught exceptions in the core for incomplete monitor information given when positioning notifications
✅ [Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b3b929d54b21953031f3673)
✅ [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b3b93c454b21953031f3674)

RUN-4237 fixed exceptions thrown for invalid monitor info

---

Gruntfile.js

ℹ️ **About**
This PR removes repetition in grunt tasks

removed repetitive grunt tasks

---

Gruntfile.js
npm-shrinkwrap.json
package.json

`electron-rebuild` was severely outdated and required updating for the new port discovery transport strategy.
✅ [Win 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b47a00054b21953031f3700)
✅ [Win 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b479ebf54b21953031f36fe)

RUN-4169 Bump electron-rebuild version and refactor

---

Gruntfile.js

Noticed this in `hadouken-js-adapter`

Do not sign ofds files

---

src/renderer/api-decorator.js

RUN-4316 application-initialized event now returns uuid

---

src/browser/api/application.js
src/browser/api_protocol/api_handlers/mesh_middleware.ts

Tests: [7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b52514154b21953031f3794) [10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b52525254b21953031f3795)

RUN-4270 Runtime version on getInfo

---

src/browser/port_discovery.ts

Note: This issue is fixed in .34

Fix error stemming from port discovery refactor

---

npm-shrinkwrap.json
package.json

Also did the npm shrinkwrap dance
Tests well
[win 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b69025854b21953031f38e5) - all pass
[win 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b6900ff54b21953031f38e4) - all pass

bumped hadouken-js-adapter to 0.34.1-alpha.3

---

npm-shrinkwrap.json
package.json

[Win10 x64](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b6cbfbb54b21953031f3935)
[Win10 x32](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b6cbfab54b21953031f3934)
[Win7 x64](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b6cbea954b21953031f3932)
[Win7 x32](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b6cbeb554b21953031f3933)

Updated version of js-adapter

---

src/browser/api/window.js
src/shapes.ts

This PR is persistent zoom level for each window. 
[Add a new test for this feature ](https://testing-dashboard.openfin.co/#/app/tests/5b6b52a254b21953031f3911/edit)
Integration Tests:
[Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b6c59d954b21953031f3921)
[Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b6c587454b21953031f3920)

RUN-4088 persistent zoom level

---

src/browser/api/application.js
src/browser/api_protocol/api_handlers/application.js

This PR is adding new APIs: setZoomLevel and getZoomLevel to application.
Tests:
[Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b71d02254b21953031f3968)
[Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b71d25a54b21953031f3969)

RUN-4153 application set zoom level

---

npm-shrinkwrap.json
package.json

This PR is updating js-adapter to latest version which fixes window.wrap issue.
[Add a new Test](https://testing-dashboard.openfin.co/#/app/tests/5b898b776107b45e6d1ebbf9/edit)
[Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b898a096107b45e6d1ebbf7)
[Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b898b096107b45e6d1ebbf8)

updated js-adapter version to 0.34.4

---

src/browser/api/system.js
src/browser/api_protocol/api_handlers/system.ts

[JIRA](https://appoji.jira.com/browse/RUN-4438)
https://github.com/openfin/javascript-adapter/pull/487
https://github.com/HadoukenIO/js-adapter/pull/174
https://github.com/openfin/runtime/pull/1134

RUN-4438: System.getMachineId()

---

Gruntfile.js

✅ [Win 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b9000bd6107b45e6d1ebc1d)
✅ [Win 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b9002336107b45e6d1ebc1e)

RUN-4496 remove Object.entries polyfill; moved to NodeJS v8

---

src/browser/api/application.js
src/browser/api_protocol/api_handlers/application.js

This PR audited application APIs and fixed a few undefined issues found when an app doesn't exist. 
Tests: 
[Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b92899a6107b45e6d1ebc40)
[Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b928b016107b45e6d1ebc41)

RUN-4368 id undefined issue

---

src/browser/api_protocol/transport_strategy/elipc_strategy.ts

Split logical responsibilities in elipc send. These changes are an incremental step towards message batching.
https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b8ecc436107b45e6d1ebc05

RUN-4512 Incremental change to organize elipc send responsibilities

---

npm-shrinkwrap.json
package.json

Tests results:
[Win 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5babd189cb360141a7dfcf8a)
[Win 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5babd2aacb360141a7dfcf8b)

Bump js-adapter to v.36

---

.gitmodules
Gruntfile.js
npm-shrinkwrap.json
package.json
src/browser/runtime_p2p/peer_connection_manager.ts
src/renderer/main.js
test/peer_connection_manager.tests.ts
tsconfig.json

This change is about adding js-adapter as a submodule to ease the development.
[Runtime PR](https://github.com/openfin/runtime/pull/1212)

RUN-4705 js-adapter as a submodule

---

src/browser/api/window.js

Integration Tests:
[Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5bca1fcecb360141a7dfd10a)
[Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5bca20efcb360141a7dfd10b)
PS: getMachineId tests failed in every version.  Ignore them.

RUN-4378 Hash winposCache filename

---

src/browser/api_protocol/api_handlers/system.ts
src/browser/api_protocol/transport_strategy/ws_strategy.ts
src/browser/preload_scripts.ts

Tests: 
[Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5bc4bc5fcb360141a7dfd096)
[Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5bc4bdb5cb360141a7dfd097)

RUN-4545 Fix js error: not opened at WebSocket.send

---

src/browser/api_protocol/transport_strategy/api_transport_base.ts
src/browser/api_protocol/transport_strategy/elipc_strategy.ts

Tests:  
[Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5bb7ce13cb360141a7dfd026)
[Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5bb7cf0ecb360141a7dfd027)

RUN-4679 not log password

---

src/browser/api/channel.ts

[new test](https://testing-dashboard.openfin.co/#/app/tests/5bbe07a4cb360141a7dfd04f/edit) (yes, a multi-runtime testrunner test!!! thanks @pbaize !!)
[win7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5bbe0bbdcb360141a7dfd050)
[win10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5bbe0ca6cb360141a7dfd051)
(onDisconnection failure expected, PR not yet merged)

RUN-4684 - Multi Runtime Channel Nack

---

src/browser/api/application.js
src/common/main.ts

Tests
[W7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b96bbd56107b45e6d1ebc5b)
[W10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b96bce86107b45e6d1ebc5c)

RUN-4398: Enable chrome pages

---

.gitmodules
Gruntfile.js
npm-shrinkwrap.json
package.json
src/browser/runtime_p2p/peer_connection_manager.ts
src/renderer/main.js
test/peer_connection_manager.tests.ts
tsconfig.json

js-adapter as a submodule for ease of development
[Runtime PR](https://github.com/openfin/runtime/pull/1221)

RUN-4705 js-adapter submodule

---

src/browser/api/application.js

RUN-4480: more PR feedbacks

---

src/browser/rectangle.ts

@pbaize I officially hate the align side function :) but this is the behavior we need to validate.

Task no relocation on resize

---

src/browser/api_protocol/api_handlers/grouped_window_moves.ts

disabled en/disabling the frame while grouped

disabled disableFrame

---

src/browser/disabled_frame_group_tracker.ts
src/browser/normalized_rectangle.ts
src/browser/rectangle.ts

re-enable pushing of windows on resize in a group for set bounds

---

index.js

Revert "RUN-4596, RUN-4742: Flag-protected cache migration"

---

src/browser/api/system.js
src/browser/cached_resource_fetcher.ts
src/browser/core_state.ts

This PR is to fix the js exception issue when calling system.clearCache during app startup.  
[Windows 10 Test](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5c097759cb360141a7dfd594)

RUN-4794 Fix js exception popup issue

---

src/browser/disabled_frame_group_tracker.ts

Raise end-user-bounds-changing for grouped window leader

RUN-4811/artificially raise end-user-bounds-changing

---

src/browser/disabled_frame_group_tracker.ts

Spelling deferred

---

src/browser/of_events.ts
src/browser/remote_subscriptions.ts
src/common/main.ts

ℹ️ This PR fixes timestamps for System's remote event subscriptions
➕ New automated test: [Multi-runtime missed events (System)](https://testing-dashboard.openfin.co/#/app/tests/5c129c05cb360141a7dfd6c4/edit)

RUN-4786 fixed remote subscriptions for System

---

src/browser/disabled_frame_group_tracker.ts

[Tests well](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5c1d1168cb360141a7dfd7c7), two expected fails around animations
@pbaize please double check my "math" here.

RUN-4858 fixed setBounds when in group

---

src/renderer/node-less.js

Because of the external/internal IPC refactoring in [1], messages on the channel
ELECTRON_INTERNAL_RENDERER_ASYNC_WEB_FRAME_METHOD are now sent on an internal
bus. Nodeless sandboxed renderers are initialized in src/renderer/node-less.js,
so they need to listen on the internal bus to receieve these messages.
This needs the internal bus itself to be exported; see [2].
[1] https://github.com/openfin/runtime/commit/b50f86ef43b17f90c295349d8ca93751ad9045a6
[2] https://github.com/openfin/runtime/pull/1326

RUN-4912 et al. fix(ipc-renderer): use internal IPC in nodeless sandbox renderer

---

index.js
npm-shrinkwrap.json

Fixes a lint issue. Additionally, adds an entry for `types/ws` to shrinkwrap.
Notes: N/A - Internal

Fix lint issues and missing shrinkwrap entry

---

src/browser/web_request_handler.ts

This PR is completely removing logs for headers so SSO or any sensitive info from clients will not be logged any more.

RUN-4968 completely remove header logs

---

src/browser/disabled_frame_group_tracker.ts

Adds a guard to prevent a window "growing" during a top/left edge grouped resize
Notes:  v10 regression fix

Added guard

---

src/browser/api_protocol/api_handlers/mesh_middleware.ts

These changes ensure that multi-runtime aggregate calls don't error for the requester, causing an error callback. Instead, it will safely ignore failed aggregate calls and only include successfully retrieved data. This timing bug has been noticed when aggregate calls are made during another runtime's shutdown process.
- [Changed: Multi-runtime missed events (System)](https://testing-dashboard.openfin.co/#/app/tests/5c129c05cb360141a7dfd6c4/edit)
- [Added: Multi-runtime aggregate API call during shutdown](https://testing-dashboard.openfin.co/#/app/tests/5c66e9c2cb360141a7dfdba1/edit)
Bug fix: failed multi-runtime aggregate calls are ignored, instead of causing error callbacks or rejections in requesting APIs

RUN-4936 Fix for multi-runtime aggregate calls

---

src/renderer/api-decorator.js

added space

---

src/browser/api_protocol/api_handlers/application.js

log error message if dup uuid transport listener not unhooked properly

log error message if dup uuid transport listener not unhooked properly

---

src/renderer/api-decorator.js

This PR is to fix the message not shown issue when using openfin cli to launch an app without a valid license key.

RUN-4958 Fix a warning message not shown issue

---

src/browser/normalized_rectangle.ts

Translate resizable: false to rectangle options and adjust size constraints for the window frame
Improved behavior of constrained windows in groups.

RUN-5079 RUN-5078 Resizable in a group and framed constrained windows

---

index.js

Log system memory info on startup.

RUN-5130 Log system memory info on startup

---

src/renderer/api-decorator.js
src/renderer/node-less.js

Use upstream version of web frame api. This allows removal (well not applying to be more specific) of conflicting native code changes.

RUN-5170: Update code to upstream changes.

---

src/browser/api/native_window.ts
src/browser/api/window.js
src/renderer/api-decorator.js
src/renderer/node-less.js

Updated the code to upstream changes and made some fixes for spotted problems.

Run 5149: Changes and fixes made in v12 intake to electron 5.0.0-beta.8.

---

src/browser/api/window.js

This PR is to turn app log on by default. It requires RVM change. Should work with RVM change.
-->

RUN-5109 Turn app log on by default. 

---

src/electron.d.ts
src/modules.d.ts

Update types for v11, uses better types generated by https://github.com/pbaize/runtime/tree/docs-for-type-def
Runtime PR is up get these types going forward
N/A V11 update process

RUN-5180 updated types

---

index.js
src/browser/api_protocol/api_handlers/authorization.js
src/renderer/node-less.js

RUN-5199: Changes introduced in electron v6.0.0 intake.

---

src/renderer/api-decorator.js

This PR is to add some info for invalid license key in debug log. So we can add an automated test to verify if a license key is valid. 
[New Test](https://testing-dashboard.openfin.co/#/app/tests/5cd1d77ccb360141a7dfe2a5/edit)

RUN-5276 Add invalid license key info into debug log

---

src/browser/api/window.js

Revert changes for https://appoji.jira.com/browse/RUN-5200.
This resets the changes from the following PRs:
https://github.com/HadoukenIO/core/pull/782
https://github.com/HadoukenIO/core/pull/792
Notes:

RUN-5200: revert changes

---

src/browser/api/window.js
src/browser/api_protocol/api_handlers/window.ts

Making sure win.navigate nacks.
- doc change already present in canary

RUN-5060 : window.navigate should ack nack same as new fin...Window

---

src/browser/api/webcontents.ts
src/browser/api/window.js

Extract webcontents methods from window.js
First PR to allow code sharing with browserview
Notes: na

Run 5188/part 1

---

src/browser/api/notifications/shapes.ts
src/browser/api/notifications/subscriptions.ts
src/modules.d.ts

RUN-5294 Use non-primitive object type instead of boxed Object

---

src/browser/api/system.js
src/browser/api/window.js
src/browser/cached_resource_fetcher.ts
src/electron.d.ts

RUN-5297: Adapt code to upstream changes.

---

src/electron.d.ts
src/modules.d.ts

Updates typedef from the runtime. Needed for typescript update.
Notes: na

RUN-5283 updated-types

---

src/browser/api/webcontents.ts

This reverts commit 265b17c4bf12587497731f04f09f14e363455bd7.
Changes were pushed without PR, this is just house cleaning.

Revert "fixing navigateBack & navigateForward"

---

src/browser/api/webcontents.ts

Removed canGoBack & canGoForward chacks when navigating

navigation bugfix

---

src/browser/animation/tween.js
src/browser/animations.js
src/browser/api/application.js
src/browser/api/external_application.ts
src/browser/api/interappbus.js
src/browser/api/notification.js
src/browser/api/system.js
src/browser/api/window.js
src/browser/api_protocol/api_handlers/application.js
src/browser/api_protocol/api_handlers/authorization.js
src/browser/bounds_changed_state_tracker.ts
src/browser/convert_options.js
src/browser/deferred.ts
src/browser/external_window_event_adapter.ts
src/browser/monitor_info.js
src/browser/process_tracker.js
src/browser/rvm/runtime_initiated_topics/rvm_info.js

Changes exports in the core from using module.export to named exports. Required for typescript 3 upgrade
Notes: n/a

RUN-5253 change export type to es modules

---

npm-shrinkwrap.json
package.json
src/browser/api_protocol/api_handlers/grouped_window_moves.ts

Do not merge until #811 #774 are merged. This change just bumps the typescript version and includes one small change to handle a breaking change from the upgrade.
- [] `npm test` passes
Notes: n/a

Run 5254 Upgrade to Typescript 3.5

---

src/browser/animations.js
src/browser/api/external_window.ts
src/browser/api/system.js
src/browser/api_protocol/api_handlers/clipboard.ts
src/browser/external_window_event_adapter.ts
src/browser/navigation_validation.ts
src/browser/session.ts
src/browser/transports/chromium_ipc.ts
src/browser/utils.ts
src/electron.d.ts
src/modules.d.ts
src/shapes.ts

electron.d.ts is up to date and commited as it was generated.
It does not contain any manual changes. Did some docs and code fixing
on runtime side and code cleanup and fixing here to make it possible.

 RUN-5331: Resync electron type definitons and remove redundant ones.

---

src/browser/api/external_window.ts

RUN-5356 fix develop build

---

src/browser/api/external_window.ts
src/electron.d.ts

Jira: https://appoji.jira.com/projects/RUN/issues/RUN-5272
Related js-adapter change: https://github.com/HadoukenIO/js-adapter/pull/294

Run 5272 no non-existent hwnd

---

src/browser/api/external_window.ts

Fixes all, except one, TypeScript errors for external windows.
N/A

RUN-5366 fixes TS errors for external windows

---

src/electron.d.ts

RUN-5307: Update electron.d.ts

---

src/electron.d.ts

RUN-5386: Updated electron.d.ts

---

src/electron.d.ts

RUN-5307: Updated src/electron.d.ts

---

src/browser/api/window.js
src/browser/api_protocol/api_handlers/api_policy_processor.ts
src/browser/api_protocol/api_handlers/system.ts
src/browser/api_protocol/shapes.ts
src/shapes.ts

Tests
[W10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5cdcce01cb360141a7dfe3af)
[W7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5cdccd4bcb360141a7dfe3ae)
14 tests failed because default permission for the following APIs is FALSE:
.downloadAsset
.launchExternalProcess
.readRegistryValue
.terminateExternalProcess
Will fix these tests shortly

RUN-5291: Secure API for real phase 1

---

.github/CONTRIBUTING.md
NOTICE
README.md
src/browser/api/external_window.ts
src/browser/api/window.js
src/browser/api_protocol/api_handlers/api_policy_processor.ts
src/browser/api_protocol/api_handlers/api_protocol_base.ts
src/browser/api_protocol/api_handlers/external_window.ts
src/browser/api_protocol/api_handlers/grouped_window_moves.ts
src/browser/api_protocol/api_handlers/system.ts
src/browser/api_protocol/shapes.ts
src/browser/api_protocol/transport_strategy/api_transport_base.ts
src/browser/api_protocol/transport_strategy/elipc_strategy.ts
src/browser/core_state.ts
src/browser/window_groups.ts
src/modules.d.ts
src/renderer/api-decorator.js
src/renderer/main.js
src/renderer/node-less.js
src/shapes.ts

Merge develop into v13 develop

---

src/electron.d.ts

RUN-5408: Updated electron.d.ts

---

.github/PULL_REQUEST_TEMPLATE.md

Added to checklist items: 
Links to newly created tests for review
PR was assigned to reviewers.
Internal change, not relevant.

RUN-5305 Added reviewer and test link items to the PR template

---

src/electron.d.ts

RUN-5409: Updated electron.d.ts

---

src/electron.d.ts

RUN-5439: Updated electron.d.ts

---

src/electron.d.ts

RUN-5464: Updated electron.d.ts for Electron 6.0.0

---

src/browser/api/window.js
src/electron.d.ts

Merge 13.76.43/staging to 13/develop

---

src/browser/api/window.js

[n/a] removed dead code that should not work

---

src/browser/core_state.ts

!A&!B !== !(A&B)

---

src/browser/api/browser_view.ts

Add a check of whether the name provided in options is already in use within the same application by either another browser view or a window.
Notes: Limited BrowserView identities to unique names
@pbaize @rdepena @bschwinn

RUN-5489   BrowserView name should be unique

---

src/electron.d.ts
src/modules.d.ts

RUN-5477: Updated electron.d.ts and modules.d.ts

---

src/electron.d.ts

RUN-5499: Updated electron.d.ts

---

src/renderer/node-less.js

Add a finally block to api injection
Notes:

RUN-5512 added finally block

---

src/browser/api_protocol/index.ts
src/browser/api_protocol/transport_strategy/elipc_strategy.ts
src/browser/api_protocol/transport_strategy/ws_strategy.ts
src/browser/transports/socket_server.ts

Added logging of cpu and memory usage around windowing and messaging

---

src/electron.d.ts

RUN-5590: Updated electron.d.ts

---

src/electron.d.ts

RUN-5537: Updated electron.d.ts

---

src/browser/api/browser_view.ts
src/browser/api_protocol/api_handlers/browser_view.ts

Expose view.destroy to remove browserviews
https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5d8002367bacba7f712054c8
Notes: n/a experimental

RUN-5608 exposed view.destroy

---

src/browser/api/window.js

Add missing name for Window.getViews
Tests: https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5d7ff6957bacba7f712054bb
Notes:

RUN-5469 Added name to getCurrentViews

---

src/browser/api/application.js
src/browser/api_protocol/api_handlers/application.js

fixed type overwrite
added safeguard and remove unnecessary comment'
Notes:

RVM-976: createFromManifest changes

---

src/electron.d.ts

RUN-5613: Updated electron.d.ts

---

src/browser/api/system.js
src/browser/cached_resource_fetcher.ts

This PR is to fix uncaught js exception in main process found by GS.

RUN-5262 Uncaught js exception in main process

---

src/electron.d.ts
src/modules.d.ts

RUN-5629: Updated electron.d.ts and modules.d.ts

---

src/electron.d.ts
src/modules.d.ts

RUN-5631: Updated electron.d.ts and modules.d.ts

---

src/electron.d.ts
src/modules.d.ts

RUN-5641: Updated electron.d.ts and modules.d.ts

---

src/electron.d.ts

RUN-5645: Updated electron.d.ts

---

src/browser/api_protocol/api_handlers/api_policy_processor.ts

Makes BrowserViews respect api permissions. @licui3936 already added tests
- x ] PR title starts with the JIRA ticket [pull request process](https://github.com/openfin/Internal-Wiki/wiki/Pull-Request-Process)
Notes:

RUN-5468/ respect api permissions for browserviews

---

src/browser/api/browser_view.ts
src/browser/api/window.js
src/browser/api_protocol/api_handlers/webcontents.ts
src/browser/api_protocol/api_handlers/window.ts
src/browser/core_state.ts
src/browser/preload_scripts.ts
src/browser/window_groups_runtime_proxy.ts
src/shapes.ts

Added Preload script support for browserview
https://testing-dashboard.openfin.co/#/app/tests/5d890db17ba87401eaf56608/edit
Notes: n/a experimental

RUN-5567 Added preloadscripts for browserviews
